nightwatchjs/nightwatch

- package.json
> Move grunt to devDependencies

- lib/runner/cli/cli.js
- lib/runner/cli/clirunner.js
- lib/runner/module.js
- lib/runner/testsuite.js
- tests/sampletests/withfailures/sample.js
- tests/src/runner/testRunner.js
Reruns entire test suite on failure. Might need some refactoring..
> Add suiteRetries option

- lib/api/expect.js
- lib/api/expect/_baseAssertion.js
- lib/api/expect/attribute.js
- lib/api/expect/css.js
- lib/api/expect/type.js
- tests/src/expect/testExpectAttribute.js
- tests/src/expect/testExpectCss.js
- tests/src/expect/testExpectType.js
Also added a test to testExpectAttribute and examples in comments of all expect assertions.
> Added optional message to expect assertions as requested in issue #507.

- lib/index.js
- lib/runner/clientmanager.js
- lib/runner/testsuite.js
Fixes https://github.com/nightwatchjs/nightwatch/issues/610, https://github.com/nightwatchjs/nightwatch/issues/588, https://github.com/nightwatchjs/nightwatch/issues/614
> Fix retry issues

- README.md
we've (the SeleniumHQ org) updated our wiki location
> update jsonwireprotocol link

- bin/nightwatch.json
> Add TestingBot config sample

- lib/page-object/page-utils.js
- tests/extra/pageobjects/pageObjElementsArray.js
- tests/src/testPageObject.js
This makes it easier to share elements across page objects.
> Add support for page objects element property to accept an array

- README.md
Link was broken, returning 404.
> Fixed README link to the Getting Started page.

- lib/runner/selenium.js
see issue description in #1738 
Thanks !
> New SENTINEL string for selenium 3.10.0

- lib/runner/matchers/filename.js
- test/src/runner/testRunWithExclude.js
> fix: make match logic consider any match

- .github/stale.yml
Adding this because i believe that the [stale bot](https://github.com/apps/stale) could help with maintaining this project, by automatically closing stale issues.
Before merging this, the stale bot must be activated at the link above.
> [Enhancement] Add stale bot

- lib/transport/jsonwire/actions.js
- test/src/api/protocol/testFrame.js
> Fixed #1976 - .frame(0) throwing an error

- lib/runner/cli/cli.js
- lib/runner/global-reporter.js
- lib/runner/test-runners/default.js
This is an attempt at fixing #1205 - I have fixed the original bug but some tests are failing and I cannot understand why. The test output is not very verbose and it does not point me in any direction.
Also I would have like to add a test case that reproduces the original bug but was not able to.
I'm opening this as WIP because I need some pointers
> Fix global reporting in parallel mode (fixes #1205)

- lib/runner/folder-walk.js
- lib/util/utils.js
- test/src/runner/testRunner.js
- test/src/util/testUtils.js
Fix Utils.flattenArrayDeep() so it properly handles being passed a null array by returning null.
> Fix for Issue #1987

- lib/api/protocol.js
- lib/transport/jsonwire/actions.js
- lib/transport/transport.js
- test/src/runner/testRunnerSessionCreate.js
This is a minor PR correcting function name spelling.
> Correct spelling from sreenshot -> screenshot

- examples/globalsModule.js
Issue: https://github.com/nightwatchjs/nightwatch/issues/2044
> syntax fixed

- lib/transport/jsonwire/actions.js
fixes https://github.com/nightwatchjs/nightwatch/issues/2026
> fixes switching to frame

- lib/api-loader/page-object.js
- test/extra/pageobjects/pages/api/method/bar.js
- test/extra/pageobjects/pages/api/method/foo.js
- test/src/element/testPageObjectElementSelectors.js
> fix nested page objects #2077

- lib/page-object/command-wrapper.js
- test/src/core/testPageObjectCustomCommands.js
> Fixed condition in isPossibleElementSelector

- lib/transport/webdriver/actions.js
fixing https://github.com/nightwatchjs/nightwatch/issues/2150
> fix W3C window maximize to be a POST command

- lib/api/protocol/keys.js
> api-docs: update keys

- lib/http/auth.js
> chore: removed unused function variable from authorization

- package-lock.json
- package.json
> remove 8 of 14 vulnerabilities with npm update

- lib/runner/folder-walk.js
- test/src/runner/testRunWithTags.js
Closes https://github.com/nightwatchjs/nightwatch/issues/2417
> Fix --filter being ignored when --skiptags is set

- lib/runner/concurrency/child-process.js
- package.json
- test/src/runner/cli/testParallelExecution.js
Hi all - this PR fixes issue #2438 (please see issue for a detailed description.)
@beatfactor @Topperfalkon let me know if there's anything else that may need further explanation - always happy to update or re-think based on your perspective. Thanks again for maintaining nightwatch.
> Issue#2438 - fix to preserve execArgv in child process (concurrent testing)

- lib/api/client-commands/switchWindow.js
> api-docs: update switchWindow

- package-lock.json
- package.json
https://github.com/nightwatchjs/nightwatch/issues/2609
> fix: Vulnerability in v1.5.1 - ejs

- lib/api/element-commands/_waitForDisplayed.js
- lib/api/element-commands/isVisible.js
> fix safari response for validation

- lib/element/index.js
- test/extra/pageobjects/pages/simplePageObjDefaultXpath.js
- test/src/element/testPageObjectElementSelectors.js
Proposed this in discussion section.
I believe it's a small change.
Don't think so.
Check.
Might be room for improvement.
Check.
> [improvement] setting locate strategy page objects

- lib/api/_loaders/_base-loader.js
- lib/api/protocol/_base-action.js
- lib/runner/folder-walk.js
- lib/runner/test-source.js
- lib/testsuite/context.js
- lib/utils/index.js
- test/src/api/protocol/testExecute.js
- test/src/runner/cli/testCliRunner.js
- test/src/utils/testUtils.js
Based on #2064 submitted by @lloiser and #1966 by @floriansimon1.
> Added support for loading typescript .ts files

- package-lock.json
- package.json
- test/sampletests/typescript/sample.ts
- test/src/runner/cli/testParallelExecution.js
- test/src/runner/testRunnerTypeScript.js
Add a simple .ts test for #2620
> Add a test for typescript files

- lib/api/assertions/_assertionInstance.js
> remove redundant assignment

- lib/api/expect/assertions/element/_element-assertion.js
- lib/utils/index.js
- test/src/api/commands/testWaitForElementPresent.js
- test/src/api/commands/testWaitForElementVisible.js
> custom message with only time(%d) placeholder #2532

- README.md
> update readme for build status

- lib/reporter/results.js
- test/src/runner/testRunWithGlobalHooks.js
> add timestamp in result

- lib/api/_loaders/assertion-scheduler.js
- lib/api/client-commands/end.js
- lib/api/client-commands/saveScreenshot.js
- lib/testsuite/index.js
- test/src/api/commands/testEnd.js
- test/src/runner/testRunnerScreenshotsOutput.js
> save screenshots

- test/src/api/assertions/testDomPropertyEquals.js
- test/src/api/assertions/testHidden.js
- test/src/api/commands/testWaitForElementNotVisible.js
- test/src/runner/testRunnerUnitTests.js
> fix flaky tests

- lib/transport/selenium-webdriver/method-mappings.js
> user-prompt method-mapping for selenium-webdriver

- .github/workflows/build-node.yaml
- package.json
> bail after test fails

- lib/api/_loaders/_base-loader.js
- lib/runner/folder-walk.js
- lib/settings/defaults.js
- lib/utils/index.js
- package-lock.json
- test/sampletests/before-after/sampleSingleTest.js
- test/sampletests/before-after/sampleWithBeforeAndAfter.js
- test/sampletests/before-after/sampleWithBeforeAndAfterNoCallback.js
- test/sampletests/es6await/selenium/failures/sampleWithFailures.js
- test/sampletests/mixedFiles/sampleJs.js
- test/sampletests/mixedFiles/sampleTs.ts
- test/sampletests/suiteretries/locate-strategy/suiteRetriesLocateStrategy.js
- test/sampletests/suiteretries/sample/suiteRetriesSample.js
- test/sampletests/usexpath/sample.js
- test/sampletests/withasynchooks/sampleAsyncHooks.js
- test/sampletests/withelementerrors/sampleTestWithElementError.js
- test/sampletests/witherrors/sampleWithError.js
- test/sampletests/withexclude/excluded/excluded-module.js
- test/sampletests/withexclude/excluded/not-excluded.js
- test/sampletests/withexclude/simple/sample.js
- test/sampletests/withfailures/sample.js
- test/sampletests/withsubfolders/simple/sample.js
- test/sampletests/withuncaughterrors/demoTestFine.js
- test/sampletests/withwebdriver/sampleTestUsingSeleniumWebdriver.js
- test/sampletests/withwebdriver/sampleTestUsingWebdriverIO.js
- test/src/runner/cli/testParallelExecution.js
- test/src/runner/testRunnerMixedFiles.js
- test/src/utils/testUtils.js
> Fixes #2677 - add option to disable typescript

- .coveralls.yml
- .github/workflows/coverage.yml
- codecov.yml
- package.json
> add codecov coverage job

- lib/api/assertions/_enabled.js
- lib/api/assertions/enabled.js
- lib/api/element-commands/isEnabled.js
- test/src/api/assertions/testEnabled.js
- test/src/api/commands/testIsEnabled.js
> added isEnabled command

- lib/api/assertions/selected.js
- lib/api/element-commands/isSelected.js
- test/src/api/assertions/testSelected.js
- test/src/api/commands/testIsSelected.js
> Features/ isSelected element command

- lib/api/_loaders/command.js
- lib/core/treenode.js
> fix linter

- lib/api/element-commands/_waitFor.js
- test/src/api/commands/testWaitForElementVisible.js
> use locate strategy from args when valid strategy is found

- lib/settings/settings.js
- test/src/index/testSettings.js
> recursively append properties from super-env in test-settings

- test/src/api/commands/testMaximizeWindow.js
- test/src/api/commands/testWindowCommands.js
- test/src/api/commands/testWindowCommandsW3C.js
- refactored test cases for window commands.
> Refactor testcases for window commands

- lib/transport/selenium-webdriver/method-mappings.js
> update: method-mapping for elements, and frames

- lib/transport/selenium-webdriver/method-mappings.js
- test/src/api/commands/testGetLog.js
- Refactored method-mappings for session-logs
- Changed a test-case for testGetLog
> Method mapping for session logs

- lib/transport/selenium-webdriver/method-mappings.js
> feat: add method mappings for few more elements

- test/src/api/assertions/testAttributeContains.js
- test/src/api/assertions/testAttributeEquals.js
- test/src/api/assertions/testContainsText.js
- test/src/api/assertions/testCssClassPresent.js
- test/src/api/assertions/testCssProperty.js
- test/src/api/assertions/testDomPropertyContains.js
- test/src/api/assertions/testDomPropertyEquals.js
- test/src/api/assertions/testElementPresent.js
- test/src/api/assertions/testEnabled.js
- test/src/api/assertions/testHidden.js
- test/src/api/assertions/testSelected.js
- test/src/api/assertions/testTitle.js
- test/src/api/assertions/testTitleContains.js
- test/src/api/assertions/testUrlContains.js
- test/src/api/assertions/testUrlEquals.js
- test/src/api/assertions/testValue.js
- test/src/api/assertions/testValueContains.js
- test/src/api/assertions/testVisible.js
- refactored all the assertion test files.
> refactor assertions test

- lib/transport/selenium-webdriver/options.js
- test/src/index/testChromeOptions.js
- test/src/index/testEdgeOptions.js
- test/src/index/testFirefoxOptions.js
- test/src/index/testSafariOptions.js
- added tests for driver options.
- replaced `androidChrome` option with `androidPackage` for edge driver (not supported by selenium-webdriver)
> Capabilites for drivers

- lib/transport/browserstack/index.js
- lib/transport/factory.js
- lib/transport/selenium-webdriver/index.js
- fixed browserstack transport to work with selenium-webdriver
> Browserstack transport

- test/src/core/testCreateSession.js
- test/src/core/testPageObjectCommands.js
- test/src/core/testRequestWithCredentials.js
- refactored test cases in `/src/core`
> Refactor core test cases

- test/src/index/testCreateTransport.js
- refactor BrowserStack transport testcases
> refactor browserstack transport test cases

- LICENSE.md
- README.md
- bin/show_survey.js
- lib/api/_loaders/static.js
- lib/api/assertions/enabled.js
- lib/api/element-commands/findElement.js
- lib/api/element-commands/findElements.js
- lib/api/element-commands/setPassword.js
- lib/reporter/global-reporter.js
- lib/runner/cli/cli.js
- lib/runner/concurrency/concurrency.js
- lib/runner/test-source.js
- lib/testsuite/index.js
- lib/utils/index.js
- package-lock.json
- package.json
- test/extra/parallelism-workers.conf.js
- test/src/runner/cli/testCliRunnerParallel.js
- test/src/runner/cli/testParallelExecution.js
> merge main

- examples/custom-commands/strictClick.js
- added `strictClick` custom command
> strict click custom command

- lib/transport/selenium-webdriver/method-mappings.js
- status=0 in case no elements are found  but the command executed successfully.
> status positive in case no elements are found

- lib/runner/wd-instances/edgedriver.js
- test/src/wd-manager/testWebdriver.js
> Change: default port for edge

- test/lib/command-mocks.js
- test/src/api/commands/cookies/testCookie.js
- added remaining tests for cookie commands.
> Test for cookie client commands

- test/src/api/commands/element/testGetElementRect.js
- test/src/api/commands/element/testGetElementSize.js
- test/src/api/commands/element/testGetLocation.js
> Add: Missing test cases

- test/src/utils/testUtils.js
- refactored a utils test case
> refactor testUtils

- lib/transport/selenium-webdriver/method-mappings.js
- test/lib/mocks/mocks-w3c.yaml
- test/src/element/testElementCommands.js
> fix: elements tests

- package-lock.json
- test/src/cli/testCliRunner.js
- test/src/cli/testCliRunnerGenerate.js
- test/src/cli/testParallelExecution.js
- test/src/cli/testParallelExecutionExitCode.js
- test/src/utils/testUtils.js
The PR fixes the cli tests failures due to changes in v2. There are certain mocked modules that cause issues down the libs used (selenium-webdriver) and hence duplicating those functions by fake mocking them to ensure they are available for the libs.
> add cli tests

- test/apidemos/cookies/cookieTests.js
- test/apidemos/cookies/cookieTestsWithError.js
- fix for cookie tests in apidemos
> fix test for cookies in apidemos

- lib/api/_loaders/ensure.js
- test/apidemos/ensure/ensureTest.js
- test/apidemos/ensure/ensureTestError.js
- test/lib/command-mocks.js
- test/src/apidemos/ensure/testEnsure.js
- added a sample test for `ensure` apis
> Ensure api tests

- lib/api/expect/_baseExpect.js
- lib/api/expect/cookie.js
- lib/transport/selenium-webdriver/method-mappings.js
- test/src/api/expect/testExpectCookie.js
> fix: testExcept cookie tests

- lib/api/protocol/forward.js
change backwards to forwards for .forward() method
> api-docs: update forward

- .github/workflows/build-node.yaml
- lib/api/client-commands/perform.js
- lib/api/protocol/waitUntil.js
> feat: enable github action for v2

- lib/runner/cli/nightwatch.conf.ejs
- test/src/cli/testCliRunnerGenerate.js
- update auto-generated nightwatch conf to use `w3c:true`
> update default conf to use w3c driver

- lib/api/element-commands/dragAndDrop.js
- fixed the description of the element-command `dragAndDrop`
> update description of dragAndDrop element-command

- test/src/api/commands/element/testIsVisible.js
> Added test case - #2539

- lib/transport/selenium-webdriver/index.js
- lib/transport/selenium-webdriver/options.js
- test/src/index/transport/testIeOptions.js
Fixes: https://github.com/nightwatchjs/nightwatch/issues/2983
> fix: build is broken in IE (browserstack)

- lib/api/assertions/textEquals.js
- test/src/api/assertions/testTextEquals.js
Related issue: https://github.com/nightwatchjs/nightwatch/issues/3002
> Feat: textEquals assertion

- test/src/api/commands/element/testGetFirstElementChild.js
- test/src/api/commands/element/testGetLastElementChild.js
- test/src/api/commands/element/testGetNextSibling.js
- test/src/api/commands/element/testGetPreviousSibling.js
- test/src/api/commands/element/testHasDescendants.js
> Refactoring tests for commands

- test/apidemos/expect-global/expect.js
- test/lib/command-mocks.js
- test/src/apidemos/expect-global/testExpect.js
- added basic high level test for `expect(element.command)`
> added high-level tests for expect()

- test/src/api/expect-global/testElementProperty.js
- added test for `expect(element.property))`
> added test for expect(element.property)

- lib/api/expect/assertions/element/present.js
- test/src/api/expect/testExpectPresent.js
> fix(expect): element not present error

- lib/api/expect/assertions/element/present.js
- test/src/api/expect/testExpectPresent.js
Reverts nightwatchjs/nightwatch#2977
> Revert "fix(expect): element not present error"

- lib/transport/selenium-webdriver/service-builders/base-service.js
- lib/transport/selenium-webdriver/service-builders/selenium.js
> use type instead of cat in windows

- lib/api/assertions/elementsCount.js
- test/src/api/assertions/testElementsCount.js
- added test for `assert.elementsCount`
> Adding test for assert.elements count

- test/src/api/expect-global/testElementIsSelected.js
> tests for expect apis - isSelected

- test/src/api/expect-global/testElementIsEnabled.js
> tests for expect apis - isEnabled

- lib/transport/selenium-webdriver/method-mappings.js
- lib/transport/selenium-webdriver/service-builders/base-service.js
- test/lib/nocks.js
- test/src/api/commands/element/testSetAttribute.js
- test/src/api/expect-global/testElementAttribute.js
- test/src/api/expect/testExpectTitle.js
- test/src/api/expect/testExpectUrl.js
- test/src/api/expect/testExpectVisible.js
- test/src/service-builders/testSeleniumServer.js
> fix failing tests

- test/src/utils/testStackTrace.js
> update tests for testStackTrace

- lib/utils/requireModule.js
- test/sampletests/withuknownRequire/sample.js
- test/src/runner/testRunTestcase.js
Fixes: https://github.com/nightwatchjs/nightwatch/issues/3086
> fix: 'RangeError: Maximum call stack size exceeded' when using require

- lib/transport/selenium-webdriver/service-builders/chrome.js
- test/src/service-builders/testChromeDriver.js
closes: https://github.com/nightwatchjs/nightwatch/issues/3124
> fix: mutiple shell opening issue in windows

- package-lock.json
- package.json
> fixed #3154 - peerdependency of chromedriver

- README.md
Fixes [3169](https://github.com/nightwatchjs/nightwatch/issues/3169).
> Update ChromeDriver URL

- lib/api/element-commands/moveToElement.js
- lib/api/protocol/moveTo.js
- x and y offset are taken from the center of the web Element provided so changed docs for that.
> update x,y offset docs for moveToElement command

- lib/transport/selenium-webdriver/method-mappings.js
- test/src/api/commands/testSendKeys.js
> Fix #3045 - passing undefined args in array by sendkeys command was failing 

- package-lock.json
- package.json
Update glob version to fix windows issue.
ref: https://github.com/isaacs/node-glob/issues/467#issuecomment-1127830867
> update glob version

- lib/core/client.js
- test/src/index/transport/testAppiumOptions.js
Fixes https://github.com/nightwatchjs/nightwatch/issues/3166
> Fixes #3166 - Add Platform methods in case of Appium client

- README.md
Update readme with new installation instructions
> Update readme with new installation instructions

- lib/utils/safeStringify.js
- test/src/utils/testUtils.js
- added a case to handle `Proxy` Object in Safe JSON class
- fixes #3163
> handle proxy object to safely stringify

- lib/api/assertions/elementNotPresent.js
- lib/api/protocol/openNewWindow.js
> fix: documentation for few commands

- lib/api/client-commands/captureBrowserExceptions.js
- lib/api/client-commands/captureNetworkRequests.js
- lib/api/client-commands/enablePerformanceMetrics.js
- lib/api/client-commands/getPerformanceMetrics.js
- lib/api/client-commands/mockNetworkResponse.js
- lib/api/client-commands/setDeviceDimensions.js
- lib/api/client-commands/setGeolocation.js
- lib/api/client-commands/takeHeapSnapshot.js
- test/src/api/commands/client/testCaptureNetworkRequests.js
- test/src/api/commands/client/testEnablePerformanceMetrics.js
- test/src/api/commands/client/testGetPerformanceMetrics.js
- test/src/api/commands/client/testMockNetworkResponse.js
- test/src/api/commands/client/testSetDeviceDimensions.js
- test/src/api/commands/client/testSetGeolocation.js
- test/src/api/commands/client/testTakeHeapSnapshot.js
> Minor jsdoc updates in CDP commands.

- package-lock.json
- package.json
- Update `selenium-webdriver` to 4.3.1
- fixes #3247 
- #3097
> update selenium-webdriver version

- lib/http/request.js
- test/src/index/testNightwatchIndex.js
fixes #3096 
There are now 2 unit tests testing redirections with absolute and relative urls.
> Fix #3096 - preserve host when redirect points to relative url

- lib/utils/logger/index.js
- package-lock.json
- package.json
- test/src/runner/testRunnerHtmlOutput.js
> Fix #3264 converted raw html to string

- lib/api/protocol/contexts.js
- lib/api/protocol/status.js
fixes https://github.com/nightwatchjs/nightwatch-www/issues/25
> Cleaned External broken links

- lib/api/protocol/keys.js
- deprecate `keys`  protocol command
- fixes #3290
> deprecate keys protocol command

- .github/label-commenter-config.yml
- .github/workflows/label-commenter.yml
> Adds label commenter to help triage things.

- lib/index.js
- lib/runner/cli/argv-setup.js
- lib/runner/cli/cli.js
Fixes https://github.com/nightwatchjs/nightwatch/issues/3231
Output after using `--list-files` flag:
> Add:  flag in nightwatch cli

- lib/settings/settings.js
- lib/transport/selenium-webdriver/browserstack.js
- test/src/index/transport/testBrowserstackTransport.js
> Added buildname to settings when running on browserstack cloud

- lib/api/client-commands/captureBrowserConsoleLogs.js
- lib/api/client-commands/captureBrowserExceptions.js
- lib/api/client-commands/captureNetworkRequests.js
- lib/api/client-commands/enablePerformanceMetrics.js
- lib/api/client-commands/getPerformanceMetrics.js
- lib/api/client-commands/mockNetworkResponse.js
- lib/api/client-commands/setDeviceDimensions.js
- lib/api/client-commands/setGeolocation.js
- lib/api/client-commands/takeHeapSnapshot.js
Updated the JSDoc for CDP commands to match with the latest updates to JSDoc in Nightwatch types.
> Update JSDoc for CDP commands.

- lib/api/_loaders/command.js
- test/apidemos/custom-commands/testUsingCustomGetEmail.js
- test/extra/commands/es6async/getEmail.js
- test/src/apidemos/custom-commands/testCustomCommandsAsync.js
- https://github.com/nightwatchjs/nightwatch/issues/3352
- Added _reportProtocolErrors_ function inside the _instance_ class which was not present previously and it was the root cause of the bug.
- some fixes for error messages
- added testcases
> Fix#3352 Custom command throwing TypeError while returning error

- lib/testsuite/context.js
- lib/testsuite/index.js
- lib/testsuite/interfaces/describe.js
- test/sampletests/withdescribe/skipped/skipBeforeAfterEach.js
- test/src/runner/testRunTestcase.js
> Skipped running test if test is marked as xtest

- lib/runner/cli/nightwatch.conf.ejs
> Fix #3299 Outdated links in config file

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
The current Issue templates are too cumbersome to complete. Removed some fields and made fields optional. People will fill in the details if required.
> update issue template

- lib/api/index.js
- package-lock.json
- package.json
- test/src/core/testPlugins.js
- test/src/index/testProgrammaticApis.js
- test/src/service-builders/testChromeDriver.js
- test/src/service-builders/testEdgeDriver.js
- test/src/service-builders/testFirefoxDriver.js
- added `nightwatch-axe-verbose` as a dependency and auto load plugin
> add nightwatch-axe-verbose as auto load plugin

- lib/api/client-commands/axeRun.js
Adding link the axe API documentation enumerating the different rule options that can be configured for the options parameter.
Adding a link back to https://www.deque.com/axe/core-documentation/api-documentation/#options-parameter to show the various options that can be passed in the options param.
> Add additional helpful link explaining axeRun options available inside axeRun.js jsdoc comments

- lib/transport/selenium-webdriver/index.js
- fix creation of driverService while reusing browser sessions
> fix driverService creation while reusing browser session

- lib/reporter/global-reporter.js
- lib/testsuite/index.js
- send raw http output from child process
- fixes #3421
> send logger http output from child process

- lib/api/_loaders/command.js
- test/src/runner/testRunWithCommandErrors.js
> socket hang up error when report_network_errors is enabled

- lib/testsuite/index.js
- test/src/runner/testRunTestsuiteWithSuiteRetries.js
> fixes/testSuiteRetries with enable_fail_fast enabled

- lib/runner/process-listener.js
https://github.com/nightwatchjs/nightwatch/issues/3475
> fix: exit code issue in the programmatic api

- lib/reporter/index.js
- lib/reporter/results.js
- lib/testsuite/index.js
- test/src/runner/testReporter.js
Added the following properties to reporter object:
- Driver Capabilities, session id
- Start/end timestamps for test module
- test status for individual tests in module
- Start/end timestamps for individual tests in module
- Added buildName, projectName to reporter module
> Added properties to reporter object

- lib/reporter/results.js
- test/src/runner/testReporter.js
fixes bug in https://github.com/nightwatchjs/nightwatch/pull/3494 when setting testcase status in reporter.
> fixed bug when setting test status in reporter

- lib/core/client.js
- test/lib/mocks/mocks-w3c.yaml
- test/src/api/commands/element/testClick.js
> Fix  #3478 click fix for iOS native app

- lib/core/client.js
- test/src/index/testMobileComponent.js
> Fix baseUrl error while running tests on Android emulator.

- lib/reporter/global-reporter.js
- lib/reporter/results.js
- test/src/runner/testReporter.js
Added Host, buildtime and timestamps to reporter. (https://github.com/nightwatchjs/nightwatch/pull/3494)
> Added host, buildtime to reporter

- package-lock.json
- package.json
- update the nightwatch-axe-verbose
> bump version of nightwatch-axe-verbose

- lib/transport/selenium-webdriver/index.js
- lib/transport/selenium-webdriver/session.js
> Fix connect info for mobile app testing.

- lib/reporter/reporters/json.js
- lib/reporter/reporters/junit.js
> Fix #3605 Write json and junit report for multiple environments

- lib/transport/selenium-webdriver/cdp.js
- lib/transport/selenium-webdriver/method-mappings.js
- test/src/api/commands/client/testMockNetworkResponse.js
> Allow multiple network mocks at the same time.

- lib/utils/analytics.js
- test/src/analytics/testAnalytics.js
Analytics events were not getting fired due to a bug. Fixed the bug and added test.
> Fix analytics issue

- lib/core/client.js
- lib/runner/cli/cli.js
- lib/runner/concurrency/index.js
- lib/runner/test-runners/default.js
- lib/utils/index.js
- test/extra/withsafari-concurrent.json
- test/src/runner/cli/testCliRunnerParallel.js
Disabling parallelism when running tests on safari browser on localhost
> Disable parallelism when running tests on safari browser

- test/src/cli/testServiceCreationFromCli.js
Disable certain tests for windows.
> Disable test for windows

- .github/workflows/build-node.yaml
- package-lock.json
- package.json
> Bump Selenium Version to 4.8.0

- lib/assertion/assertion.js
- lib/utils/index.js
- test/apidemos/expect-global/deepEqual.js
- test/src/apidemos/expect-global/testExpect.js
> Fix #3591 - stringify the object in console output

- lib/testsuite/hooks/_basehook.js
- test/sampletests/beforewithcommand/commandInsideBefore.js
- handle the case where the done callback of hook are supplied into nightwatch commands used inside hook
- fixes #3635
> update baseHook to handle hook done function inside command callback

- lib/reporter/reporters/html.js
- test/extra/reportObject.js
- test/src/runner/testRunnerHtmlOutput.js
Fixes https://github.com/nightwatchjs/nightwatch/issues/3578
> fix: incorrect build duration in HTML Report

- lib/api/_loaders/element-api.js
- lib/api/web-element/element-locator.js
- lib/api/web-element/scoped-element.js
- lib/api/web-element/scoped-elements.js
- lib/page-object/base-object.js
- lib/page-object/command-wrapper.js
- lib/page-object/index.js
- lib/page-object/section.js
- test/apidemos/web-elements/elementApiWithPageObjects.js
- test/src/apidemos/web-elements/testElementApiWithPageObjects.js
Make the new element api commands like `.find()`, `.findAll()`, etc. available on page-objects.
> Make new element api commands available on page objects.

- types/assertions.d.ts
- types/chrome-options.d.ts
- types/custom-assertion.d.ts
- types/expect.d.ts
- types/globals.d.ts
- types/index.d.ts
Add the remaining commits merged in DefinitelyTyped.
> Add missing commits from DefinitelyTyped.

- lib/core/asynctree.js
- lib/testsuite/index.js
- test/sampletests/withverify/verifySampleFailures.js
- test/src/runner/testRunWithVerify.js
> fix #3513 Dont skip tests if verify fails

- package-lock.json
- package.json
- test/src/api/commands/element/testSubmitForm.js
- test/src/runner/testRunnerSessionCreate.js
> chore: Upgrade selenium to 4.9.0

- lib/api/protocol/waitUntil.js
- test/src/api/commands/client/testWaitUntil.js
> Added default value fix for retryInterval in waitUntil with message param

- .github/workflows/type-declaration-tests.yml
- package-lock.json
- package.json
- types/tests/expect.test-d.ts
This PR adds `tsd` which can help us write tests for types
> feat: add tsd for types test

- lib/api/assertions/hasAttribute.js
- lib/core/treenode.js
- lib/reporter/index.js
- lib/reporter/reporters/minimalJson.js
- lib/reporter/results.js
- lib/runner/cli/argv-setup.js
- lib/runner/process-listener.js
- lib/runner/test-source.js
- lib/settings/defaults.js
- lib/testsuite/index.js
- lib/utils/debuggability.js
- lib/utils/logger/index.js
- test/extra/minimalJsonReporter.json
- test/mochatests/integration/sampleWithAsyncTestcase.js
- test/src/api/assertions/testHasAttribute.js
- test/src/index/testNightwatchIndex.js
- test/src/runner/testReporter.js
- test/src/runner/testRerunFunctionality.js
- test/src/runner/testRunnerRerunJsonOutput.js
> Test o11y -> v2.6

- package-lock.json
- package.json
Selenium supports 14.20.0 so we need to align.
> Moves the minimum engine support for NodeJS to 14.20.0

- package-lock.json
- package.json
> [chore]: Update Selenium to 4.10

- README.md
> Update Readme for V3

- types/page-object.d.ts
- types/tests/index.test-d.ts
> Fix types for namespaces on page-objects.

- types/page-object.d.ts
- types/tests/index.test-d.ts
> Fix elements and commands property issue with POM.

- lib/core/client.js
- test/src/index/testProgrammaticApis.js
- [ x] Create a new branch from master (e.g. `features/my-new-feature` or `issue/123-my-bugfix`);
- [ x] If you're fixing a bug also create an issue if one doesn't exist yet;
- [ x] If it's a new feature explain why do you think it's necessary. Please check with the maintainers beforehand to make sure it is something that we will accept. Usually we only accept new features if we feel that they will benefit the entire community;
- [ x] Please avoid sending PRs which contain drastic or low level changes. If you are certain that the changes are needed, please discuss them beforehand and indicate what the impact will be;
- [ x] If your change is …
> Fix - Issue #3625 - Changed to recursive merge on caps

- lib/core/client.js
- change `lodash` to `lodash.merge`
- fixes #3834
> update lodash.merge dependency in client

- package-lock.json
- package.json
- test/src/service-builders/testSafariDriver.js
> Update Selenium to 4.11

- types/assertions.d.ts
- types/custom-assertion.d.ts
- types/expect.d.ts
- types/index.d.ts
- types/page-object.d.ts
- types/tests/globalElementApi.test-d.ts
- types/tests/index.test-d.ts
- types/web-element.d.ts
> Allow `WebElement` as a possible selector in type declarations.

- lib/api/client-commands/document/executeAsyncScript.js
- lib/api/client-commands/document/executeScript.js
Once this is merged, the website repo might also require some changes (probably change the sidebar link and ensure redirect is present from `/document/execute.html` to `/document/executeScript.html`).
> Change file names for execute commands.

- test/src/cli/testCliRunnerMocha.js
- removing color param from mocha cli runner tests.
> remove color param from mocha cli runner tests

- package-lock.json
- package.json
> [chore] bump to selenium 4.13

- package-lock.json
- package.json
> CVE 2023 43646

- package-lock.json
- package.json
> remove postInstall step

- lib/runner/cli/cli.js
- test/src/runner/cli/testCliRunnerParallel.js
- allow parallelism on any selenium host
- fixes #3948
> enable parallelism on any selenium host

- lib/transport/factory.js
> add support for browserstack turboscale urls

- lib/transport/factory.js
> add check for browserstack turboscale urls

- lib/transport/factory.js
> add support for browserstack turboscale service

- lib/transport/factory.js
> add support for turboscale service name

- package-lock.json
- package.json
The latest version of the HTML reporter fixes issue #3972.
> Update html reporter to v0.3.0

- lib/runner/concurrency/worker-task.js
- test/src/runner/cli/testCliRunnerParallel.js
- add `parallel_process_delay` to worker_threads
- tests
- fixes #3947
> add parallel_process_delay in worker threads

- package-lock.json
- package.json
> upgrade selenium to 4.16

- lib/api/web-element/commands/takeScreenshot.js
> fixed `takeScreenshot` example

- lib/api/web-element/commands/getText.js
- lib/api/web-element/scoped-element.js
- test/src/api/commands/web-element/testGetText.js
- types/tests/webElement.test-d.ts
- types/web-element.d.ts
Fixes #4179  
- [ . ] Before marking your PR for review, please test and verify your changes by making appropriate modifications to any of the Nightwatch example tests (present in `examples/tests` directory of the project) and running them. `ecosia.js` and `duckDuckGo.js` are good examples to work with.
- [ . ] Create a new branch from master (e.g. `features/my-new-feature` or `issue/123-my-bugfix`);
- [ . ] If you're fixing a bug also create an issue if one doesn't exist yet;
> Feat: Added `text` as an alias for `getText`

- lib/api/web-element/commands/getProperty.js
- lib/api/web-element/scoped-element.js
- test/src/api/commands/web-element/testGetProperty.js
- types/tests/webElement.test-d.ts
- types/web-element.d.ts
fixes #4173  
- [ . ] Before marking your PR for review, please test and verify your changes by making appropriate modifications to any of the Nightwatch example tests (present in `examples/tests` directory of the project) and running them. `ecosia.js` and `duckDuckGo.js` are good examples to work with.
- [ . ] Create a new branch from master (e.g. `features/my-new-feature` or `issue/123-my-bugfix`);
- [ . ] If you're fixing a bug also create an issue if one doesn't exist yet;
> Add `.prop()` alias to `.getProperty()` command in new Element API. 

- lib/api/web-element/commands/getTagName.js
- lib/api/web-element/scoped-element.js
- test/src/api/commands/web-element/testGetTagName.js
- types/tests/webElement.test-d.ts
- types/web-element.d.ts
fixes #4175 
- [ . ] Before marking your PR for review, please test and verify your changes by making appropriate modifications to any of the Nightwatch example tests (present in `examples/tests` directory of the project) and running them. `ecosia.js` and `duckDuckGo.js` are good examples to work with.
- [ . ] Create a new branch from master (e.g. `features/my-new-feature` or `issue/123-my-bugfix`);
- [ . ] If you're fixing a bug also create an issue if one doesn't exist yet;
> Feat: Added `.tagname()` as an alias for `.getTagName()`

- package-lock.json
- package.json
> Bump ejs to 3.1.10

- package-lock.json
- package.json
> update selenium to 4.24.1

- package-lock.json
- package.json
> Bump selenium-webdriver to 4.26.0

- package-lock.json
- package.json
> Bumped selenium-webdriver from 4.26.0 to 4.27.0

- lib/reporter/reporters/junit.js
- lib/reporter/reporters/junit.xml.ejs
- test/src/runner/testRunnerJunitOutput.js
This PR adds a few improvements over PR #4370.
Also, this PR limits the change to only tests using the BDD describe syntax to contain the impact, if any.
Thanks to @Cactusbone for the initial PR.
> Pass BDD describe title to JUnit reports

- lib/api/web-element/commands/uncheck.js
**Update doc - typo check to uncheck**
> [docs] Update uncheck.js

- lib/transport/selenium-webdriver/browserstack/automateTurboScale.js
- lib/transport/selenium-webdriver/browserstack/browserstack.js
- test/src/core/testCreateSession.js
- test/src/index/transport/testBrowserstackTransport.js
> Pagination added in Build
