lib/core/api.js
There might be a better solution, but this at least ensures the right client gets passed to the page object.
What happenede before was that the page object was stuck with the first client passed in.
=> Make page objects work with more than 1 test file

lib/runner/testsuite.js
Fix adaptGlobalHook to get expected count from hookName, not hardcoded beforeEach.
Fixes `TypeError: Cannot read property 'length' of undefined ` which gets thrown if supplying a hook other than beforeEach.
=> Fix to adaptGlobalHook

lib/runner/cli/clirunner.js
Fix deprecation notice when passing firefox_profile to any test_settings.  Currently throws a TypeError.
=> Fix deprecation notice when passing firefox_profile to any test_settings

lib/core/assertion.js, tests/src/testAssertions.js
This adds the option to add a timeout (defined in globals file) before failing in assertions. The use case here is for AJAX-heavy pages where I would like the test to wait some amount of time before the validation fails.
Currently, this can be done by creating custom assertions but this is cumbersome if you know you'll want this behavior for virtually all assertion functions (visible, containsText, elementPresent, etc).
Eventually it may make sense to add a parameter (ms) to the individual assertion functions, so the timeout can be defined in a case-by-case basis, rather than globally. But for now, I find it's a huge benefit to be able to do this on a global scale (i.e., do it for every single assertion).
The timeout gets defined in the nightwatch.json file. For example: …
=> Add option to retry failed assertions

lib/runner/cli/clirunner.js, tests/src/runner/testCliRunner.js
Currently, if your configuration specifies an environment-specific selenium start_process value that differs from the global one, it will defer to the global. I think the expected behavior is to use the test-specific one.
For example a config like:
```javascript
{ 
"selenium" : { "start_process" : false },
"test_settings" : {
"default" : {
"selenium" : { "start_process" : true }
}
}
}
```
Currently defaults to start_process being false - but I think it should be true.
=> Fix to use environment-specific selenium start_process setting if available

lib/api/protocol.js, tests/src/testProtocolActions.js
The click method is necessary to simulate the real click (left/middle/rifgt button) event on browers .
It's useful for open a context menu with the right button for eg.
It's the only way, because if you execute a mouseButtonDown('right') and then a mouseButtonUp('right') on a link that triggers a wrong mouse event and it's open the link... (cf. http://stackoverflow.com/questions/29011483/right-click-with-nightwatch/29751560)
=> Added click functionality exposed through Selenium

lib/index.js, lib/runner/cli/cli.js, lib/runner/cli/clirunner.js, lib/runner/clientmanager.js, lib/runner/testcase.js, lib/runner/testsuite.js, tests/sampletests/withfailures/sample.js, tests/src/runner/testRunner.js
This adds the feature requested in https://github.com/beatfactor/nightwatch/issues/284
If you pass the command line option `--retries <n>` it will retry up to n times.
An important distinction is that it reruns the *testcase* (test method) not the entire test (all test methods in a test file). I think this is the desired behavior since you wouldn't want to rerun a passing test method and each testcase should be autonomous anyway.
Also, I assume that we would want to rerun both failing and erroring tests since the use case is to address flaky/unreliable tests, where either could happen.
Here's an example where test2 fails the first time but passes the second:
`bin/nightwatch --test examples/tests/github.js  --retries 1`
=> Add option to retry failing tests

Gruntfile.js, examples/tests/google.js, tests/nocks.js, tests/src/expect/testExpectAttribute.js, tests/src/expect/testExpectCss.js, tests/src/expect/testExpectEnabled.js, tests/src/expect/testExpectPresent.js, tests/src/expect/testExpectSelected.js, tests/src/expect/testExpectText.js, tests/src/expect/testExpectValue.js, tests/src/expect/testExpectVisible.js
This is a preview of the new upcoming assertion library in `v0.7` based on [Chai.js](http://chaijs.com). It provides a much more flexible syntax and style.
__Example:__
```js
client.url('http://google.com')
client.expect.element('#lst-ib').to.be.enabled;
client.expect.element('body').to.be.present.before(1000);
client.expect.element('#lst-ib').to.have.css('display').matches(/block/).before(2000);
client.expect.element('body').to.have.attribute('class').which.matches(/vasq$/);
client.expect.element('#hplogo').text.to.match(/Norge/).before(1000);
client.setValue('#lst-ib', 'Norway').pause(500);
client.expect.element('#lst-ib').to.have.value.equal('Norway');
client.expect.element('#lst-ib').to.be.an('input');
client.expect.element('#lst-ib').to.be.not.selected; …
```
=> Preview Chai.js based expect assertions

lib/page-object/page-utils.js, tests/extra/pageobjects/simplePageObj.js, tests/src/testPageObject.js
Since the `elements` object in the Page Object model already defaults to CSS as locate strategy,
it would remove a lot of boilerplate code to just be able to pass the selector string, and it would
encourage code readability.
I am profoundly happy to see more support going to the Page Object model and to see that basically you are implementing what we were already implementing internally. I would be glad to upgrade my code, but I believe that keeping the Page Object as uncluttered as possible is of utmost importance.
Here's a real world example of one of our Page Object selectors list:
````
selectors = {
accomodation: {
armchair: {
el:    "[id*=ChkSeat]",
label: "[for*=ChkSeat]"
},
bed: {
el:    "[id*=ChkBed]",
label: "[for*=ChkBed]"
},
cabin: {
el:    "[id*=ChkCabine]",
label: …
```
=> Allows to define elements in the Page Objects with only selector string

lib/runner/walk.js
From comment I made here:
https://github.com/nightwatchjs/nightwatch/issues/589
Added the ability to use both Filters + Tags side by side.
=> BugFix-589: Unable to provide filters & tags

README.md
I noticed the selenium download was pointing to an http URL. I changed the download URL to https for security reasons.
=> Changed Selenium download to https

lib/api/protocol.js, tests/src/testProtocolActions.js
Reference: https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/orientation
This PR adds methods to get and set the browser orientation, which can be either 'LANDSCAPE' or 'PORTRAIT'. 
We use this when we test hybrid apps.
=> Add support for "orientation"

lib/api/protocol.js, tests/src/testProtocolActions.js
In Nightwatch, the session method can only address the current session to recover info about, or delete it, however Selenium allows to retrieve info or delete sessions by their id.
The method now allows to retrieve or delete a session by id.
Fixes #623
=> Added sessionId parameter to session method.

lib/runner/cli/clirunner.js
Fixes #671.
The current implementation always exits with the exit code of the last finished child. If a previous child process exits with a non-zero code, it simply gets ignored. This causes parallel runs with failed envs to exit with 0 even when some of the envs have failed.
=> Fix parallel mode exiting with wrong exit code

lib/api/element-commands/_waitForElement.js, tests/src/commands/testWaitForElementVisible.js
This PR is for https://github.com/nightwatchjs/nightwatch/issues/687 
This PR solves the issue by trying to relocate the element again when a stale element reference error is thrown and then checks for the visibility of the element again.
=> Issue 687 - waitForElementVisible fails due to stale element reference error

lib/runner/filematcher.js, tests/src/runner/testFileMatcher.js
In relation to https://github.com/nightwatchjs/nightwatch/issues/710
=> Allow checkModuleTags to take both tag_filter and skiptags

lib/api/assertions/elementNotPresent.js, tests/src/assertions/testElementNotPresent.js
as with #716 this pr keeps in with `elementPresent` logic.  The test has been added on the basis on the comment within that PR too.
I have tested this in BrowserStack on multiple browsers and updated the status to match real output (-1)
=> Fix edge elementNotPresent

lib/core/api.js, tests/extra/pageobjects/addl/simplePageObject.js, tests/src/testPageObject.js
Adds feature requested here: https://github.com/nightwatchjs/nightwatch/issues/819
In particular, if the directory structure is:
`root_dir/foo/bar.js` (where `root_dir` is base directory)
the respective page object would be: `page.foo.bar()`
=> Require subdirectories in page object path

README.md
When cloning from Git on Windows using the command provided:
$ git clone git@github.com:nightwatchjs/nightwatch.git
I got the following response:
<details>Cloning into 'nightwatch'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.</details>
However if I use the default clone URL provided by GitHub:
$ git clone https://github.com/nightwatchjs/nightwatch.git
It works as expected: …
=> Readme: Fix git clone install command

lib/api/client-commands/perform.js
Additional clarity around callback parameters and behavior for `perform()`.  Example was expanded to include each of the variations of callback parameters.
=> Fixed #1063 Fixed #1065 - updates to perform callback documentation

test/src/api/assertions/testCssClassPresent.js
Fix typo in test names where cssClassPresent tests were named cssClassNotPresent.
=> Fixed #1078 - typo in cssClassPresent test names

lib/page-object/page.js
Adds a new callback parameter to Page.navigate() which gets forwarded to the internal call made to api.url()
=> Fixed #1046 - adds callback to page object navigate()

bin/nightwatch.json
This allows sample tests with Page Object Model example to be executed via `./bin/nightwatch -t examples/tests/googlePageObject.js`
=> add page_objects_path to config

lib/runner/cli/clirunner.js, test/src/runner/cli/testCliRunner.js
This is based on #1096 and consolidates the error response in situations when the specified test file doesn't exist/cannot be loaded. The behaviour is the same in these 2 situations:
```sh
$ nightwatch --test /path/to/invalid-file.js
$ nightwatch /path/to/invalid-file.js
```
The error message though may be somewhat less user friendly.
@senocular would you mind having a look?
=> Updated implementation for getting the test source for single files (#1096)

lib/runner/cli/clirunner.js, test/src/runner/cli/testCliRunner.js
Figured out where the cannot find --test file error was getting lost.  The error needed to be handled and sent off to the callback function that is used to catch the other errors being reported (like a missing src_folders setting). The other errors get handled in the runner which handles that callback action internally there. The --test path was throwing outside of the runner so that's now getting handled and passed to the callback on error.
=> Fixed #1091 - now catching not found --test error

.gitignore
Keeps the output folder where test run results are stored from being committed back in the repo by adding it to .gitignore.  Now, when people run the tests as part of their due diligence in submitting a new PR (like this one!), they won't have to worry about the output folder getting caught up in that PR anymore (and it wasn't!).
=> Fixed #1111 - add output to .gitignore

lib/api/element-commands.js, lib/api/element-commands/_elementByRecursion.js, lib/api/element-commands/_elementsByRecursion.js, lib/api/expect/_baseAssertion.js, lib/api/protocol.js, lib/page-object/command-wrapper.js, lib/page-object/element.js, lib/page-object/page-utils.js, lib/page-object/section.js, test/extra/pageobjects/simplePageObj.js, test/lib/nockselements.js, test/lib/utils.js, test/src/api/element-selectors/testCommandsElementSelectors.js, test/src/api/element-selectors/testExpectElementSelectors.js, test/src/api/element-selectors/testPageObjectElementSelectors.js, test/src/api/element-selectors/testProtocolElementSelectors.js
(Partial implementation of the original #1116)
Adds support for optional, object-based selector values in commands using the format used by page elements.  ex:
```js
// before:
browser.getText('#foo', function(result){});
// now (optionally):
browser.getText({selector:'#foo', locateStrategy:'css selector'}, function(result){});
```
- This new implementation reduces complexity around page command wrapping.  We no longer need to track and restore the locate strategy because its encoded directly within the selector; the callbacks are no longer wrapped.  This should presumably fix (could use verification from submitters): #1142, #1107, #1100, #895
- As a result of the above, page objects can also use any form of supported locate strategy …
=> Add support for page object-formatted object-based selectors

examples/pages/nightwatchFeatures.js, examples/tests/nightwatchByIndex.js, lib/api/element-commands.js, lib/api/element-commands/_elementByRecursion.js, lib/api/protocol.js, lib/page-object/element.js, lib/page-object/section.js, test/extra/pageobjects/simplePageObj.js, test/lib/nockselements.js, test/src/api/element-selectors/testIndexedElementSelectors.js
Allows the option of specifying an `index` property in element objects for pages or element commands (when objects are used as their selector value).  The `index` is used to target a specific element in a query that results in multiple elements returned.  Normally, only the first element is used (`index = 0`) but using the `index` property, you can specify any element within the result by its index within that result.
In element command selectors:
``` js
// targets 3rd div in document
browser.getText({selector:'div', index:3}, function(result){});
```
In page object definitions:
``` js
module.exports = {
commands: [],
elements: {
mydiv: {
selector: 'div',
index: 3 
}
}
};
```
``` js
// targets 3rd div in document
page.getText('@mydiv', function(result){});
```
Object selectors in commands …
=> fixes #1115 - adds optional index property to element objects

lib/runner/run.js
When something goes wrong and neither a test suite nor a finishCallback are given,
the processListener in run.js swallows the error. This happens when you are using
mocha as a test runner and have a syntax error or throw an exception outside of
the test suite (e.g. `require('./some-spec-helper')` while the file does not exist)
=> Fix silently swallowed exceptions

package-lock.json, package.json
This pull request fixes #1793
"optimist" was removed from dependencies in e0377111c73b350c4eb10c46fcd86183f8bab28b , but it is still used in `lib/runner/cli/argv-setup.js`.
This pull request also updates `package-lock.json` from `npm install optimist` .
=> Add missing dependency "optimist"

.travis.yml, lib/testsuite/testsuite.js, package-lock.json, test/src/api/protocol/testExecute.js
This branch is based on master, seeing as it fixes the 1.0.6 release.
This fixes #1831 by ensuring backwards compatibility with node v6, while allowing unit tests to work with the LTS of node.
=> Update node version to 8 and add support for 10 - fixes #1831

lib/api-loader/page-object.js, test/src/core/testPageObjectCustomCommands.js
In v1, custom commands are not being loaded onto page objects. This change should fix this.
I also added a test to make sure it doesn't break in the future. Before my change the test was failing.
=> Fix #1808 - load custom commands on page objects

.eslintrc, .travis.yml, examples/globalsModule.js, examples/tests/nightwatchByIndex.js, lib/core/queue.js, lib/index.js, lib/runner/test-runners/mocha.js, lib/testsuite/context.js, lib/testsuite/testsuite.js, lib/transport/jsonwire.js, lib/transport/transport.js, lib/transport/webdriver.js, lib/util/utils.js, package-lock.json, package.json, test/.eslintrc, test/lib/globals.js, test/src/api/assertions/testElementPresent.js, test/src/api/commands/testIsLogAvailable.js, test/src/api/commands/testSaveScreenshot.js, test/src/api/commands/testWaitForElementNotVisible.js, test/src/api/commands/testWaitForElementVisible.js, test/src/api/element-selectors/testIndexedElementSelectors.js, test/src/runner/cli/testCliRunner.js, test/src/runner/testRunner.js, test/src/runner/testRunnerUnitTests.js
Changes made:
- add an "indent" rule to .eslintrc to enforce correct indentation
- removed duplicate configuration in 'tests' folder,'
and just left the rules that need to be overridden for that folder
- auto fixed indentation on all files via the eslint --fix option
- re-enabled node 10 for travis checks and updated package-lock.json
with correct packages to avoid issues
=> Add eslint indent rule

lib/api/element-commands/waitForElementNotPresent.js, lib/api/element-commands/waitForElementNotVisible.js, lib/api/element-commands/waitForElementPresent.js, lib/api/element-commands/waitForElementVisible.js
Fix for issue #1891 
- Indicate time parameter is optional
- Add poll parameter
- Add default value for time, poll, abortOnFailure
=> Issue-1891: Update documentation for waitForElement commands

lib/settings/defaults.js
The `settings.setWebdriverSettings()` function merges `selenium` in `webdriver`:
```
...
} else if (this.settings.selenium) {
defaultsDeep(this.settings.webdriver, this.settings.selenium);
}
...
```
This eventually causes `setWebdriverHttpOption()` in `lib/index.js` to incorrectly treat `typeof webdriverOpts[port]` as set (`typeof webdriverOpts[newSetting] == 'number'`).
In this PR, we just set `selenium.port` to `undefined` in `lib/settings/defaults.js`. I'm not sure this is the right option here, but it looked to me to be the most straightforward, least disrupting.
Fixes https://github.com/nightwatchjs/nightwatch/issues/1949
=> Set selenium.port to undefined.

lib/api-loader/_base-loader.js, lib/api-loader/expect-element.js
[Issue 2010](https://github.com/nightwatchjs/nightwatch/issues/2010)
Fixes a typo (getOriginalStrackTrace -> getOriginalStackTrace)
=> Issue 2010 Fixes a typo (getOriginalStrackTrace -> getOriginalStackTrace)

lib/runner/matchers/tags.js, test/src/runner/testTagsMatcher.js
This pull request resolves this issue: https://github.com/nightwatchjs/nightwatch/issues/955
Old behavior (in 1.0.18): only one filter tag can be specified with `--tag`, e.g. `--tag example`.
New behavior: `--tag` accepts a comma-separated list of tags. Only tests having all of the filter tags will be run.
The pull request has two commits, I recommend to review them separately:
* the first commit is only a refactoring of testTagsMatcher.js with zero changes.
* the second commit implements the feature request from the referenced issue.
If you find the refactoring of testTagsMatcher.js unnecessary, please let me know, I will revert it and clean up.
=> Issue 955 treat multiple filter tags as AND selection

lib/runner/reporters/junit.js, lib/util/utils.js, test/src/util/testUtils.js
This is a proposed fix for https://github.com/nightwatchjs/nightwatch/issues/2004.
Currently, there are rogue control characters being included in the JUnit XML report. I felt that it would be safer to target the entire XML report at point of writing, as this is the last possible place for ensuring it's safe to write.
I have added a test for the stripping out of control characters, but felt it was unnecessary to do a duplicated full end-to-end test case with an included control character.
=> Issue 2004: Strip out control characters from Junit XML report prior to writing file

lib/transport/transport.js
I noticed this feature request #2060 so I decided to create pull request.
I added an additional condition to check **detailed_output** before print warning for waitForElements
=> feature:  Hide "waitForElement" warnings when "detailed_output:" is set to "false"

lib/api/element-commands/_waitFor.js, lib/api/element-commands/waitForElementNotPresent.js, lib/api/element-commands/waitForElementPresent.js, test/src/element/testCommandsElementSelectors.js
see #2091 
```
[My Test] Test Suite
======================
Running:  present - success
✔ Element <#hplogo> was present after 7 milliseconds.
OK. 1 assertions passed. (10ms)
Running:  not present - success
✔ Element <#foo> was not present after 8 milliseconds.
OK. 1 assertions passed. (8ms)
Running:  present - failure
✖ Timed out while waiting for element <#foo> to be present for 5000 milliseconds. - expected "found" but got: "not found"
at Object.present - failure (/home/lloiser/projects/nightwatch-testing-repo/test/wait-test.js:18:12)
at Context.call (/home/lloiser/projects/nightwatch/lib/testsuite/context.js:213:32)
at TestCase.run (/home/lloiser/projects/nightwatch/lib/testsuite/testcase.js:49:31)
at Runnable.handleRunnable [as __runFn] …
```
=> Correctly wait in waitForElementNotPresent for element not present

lib/transport/actions.js, lib/transport/jsonwire/actions.js, test/src/api/protocol/testElementCommands.js, test/src/api/protocol/testSubmit.js
Since chromedriver 75 release, tests have become unstable. Namely - chromedriver 75 has enabled w3c mode by default, and that very much contradicts the way how Nightwatch works together with Selenium grid. This can be solved by adding `w3c: false` to chrome options, but that does not fully work as chromedriver expects "id" in request body, not in path. This might be related to a [bugfix](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2719) in chromedriver, although I am not sure.
This PR adds the "id" parameters in the request body to element related requests. This likely also fixes https://github.com/nightwatchjs/nightwatch/issues/2118.
=>  Add "id" in request body for jsonwire element commands

lib/util/utils.js, test/src/util/testUtils.js
Loosen the relative(absolute) URL checking to detect `://` in position > 0, instead of checking `http(s)://` such that we can support different protocols. e.g. `file://`, `chrome-extension://`
=> Fixed #2165 - detect non-http absolute url in Util.relativeUrl

lib/api/client-commands/perform.js
When running `.perform` command with `done` callback, the command has default timeout as defined in `asyncHookTimeout` setting. If this timeout is exceeded test fails with 0 exit code, producing a false positive result (see #1301 ). By passing `this` to timeout function, we allow that function to emit error which will then be gracefully caught and exit code won't be 0 if the command fails to finish within the timeout. 
This change likely breaks tests for those who assume this behaviour, but I believe that this behaviour is faulty and deserves to be fixed.
=> Emit error if perform command times out

lib/runner/cli/cli.js, lib/util/logger.js
Hello everyone,
We have huge codebase for testing with Nightwatchjs in our company and when we were trying to update from version 0.9.21 to 1.2.1 we saw that "element" command logs a lot of information in the console. Sometimes when we analyse our test cases these unwanted logs are causing us a lot of discomfort because it's really hard to sift out the important logs.
Adding outputEnabled and other options to nightwatch.json didn't help us to suppress the log of the "element" command.
I guess that an option for disabling error logs is important feature and will help a lot for developers who are using Nightwatchjs to test the appearance of a dynamic content. For example, when using "element" command to verify a presence of an html element in order to decide the further test case steps. 
I …
=> suppress error log

lib/runner/wd-instances/base-wd-server.js, test/src/wd-manager/testSelenium.js
This exposes settings for the selenium server connection, to allow the configuration of the `maxStatusPollTries` value as well and the `statusPollInterval` value.
We ran into issues when using a Selenium server for our Nightwatch tests on Travis because Nightwatch would time out trying to connect to the Selenium server. For now, we are making use of the  `check_process_delay` setting which gives our environment more time to spin up the Selenium server, but this relies on a javascript timeout and a set amount of attempts that cannot be configured. It would be good to let developers configure those values as well to give them more flexibility in their setup.
If anything is missing or this PR does not make sense, please comment and let me know what's wrong or needs to be changed.
=> Expose status polling settings

lib/settings/defaults.js, lib/settings/settings.js, lib/utils/logger.js
There is a setting in the logger to show the timestamp when outputting a log message, but there is no way via the CLI to activate that setting. This PR adds a way to do that.
=> Add cli option for showing timestamp in logs.

lib/runner/reporters/junit.xml.ejs, test/sampletests/witherrors/sample.js, test/src/runner/testRunner.js
Hi Team,
We've started using [BuildKite](https://buildkite.com) to run our Nightwatch tests and it has a great plugin for [JUnit xml report parsing](https://github.com/buildkite-plugins/junit-annotate-buildkite-plugin). The only problem we encountered was that it wasn't picking up the errors from tests due to error information not added the the report output. I'm hoping that this pull request will benefit the community by adding both the error message and the stack trace. 
I have matched the Junit schema specified here: https://llg.cubic.org/docs/junit/
It appears in BuildKite like this:
=> JUnit xml error messages in test runner report output

lib/reporter/reporters/junit.xml.ejs
When `testcase.lastError` or `testcase.lastError.message` in junit.xml.ejs isn't truthy, Nightwatch is generating invalid XML. The line comes out like `<errortype="error">`, not `<error type="error">`.
This addresses #2396.
=> Add missing space to new error line.

lib/api/protocol/element.js
There is a small typo in lib/api/protocol/element.js.
Should read `strategy` rather than `stragy`.
=> docs: Fix simple typo, stragy -> strategy

lib/runner/wd-instances/safaridriver.js
Removed the incorrect cli args causing safari driver to exit immediately. Issue #2375. Let me know if there's anything that I've missed or need to update - thanks!
**ps. let me know if there's a need for a test in this PR. I did not find any tests related to safari at this level**
=> Remove incorrect cli args from safaridriver. Issue #2375

lib/api/expect/assertions/element/css.js
Typo: An asterisk in the wrong place that was getting rendered into the docs.
=> api-docs: update css

lib/settings/settings.js
This adds Buildkite to the list of CI providers that support coloring output.
Fixes #2422
No tests were updated because it doesn't appear there's any that cover this particular setting.
=> Add Buildkite to CI coloring support

lib/api/client-commands/getCookie.js, lib/api/client-commands/getCookies.js, lib/api/client-commands/setCookie.js
This is purely a documentation update. There are some links to the old Google Code Selenium wiki for the Cookies API reference, which no longer exists. I've found the correct links on the new wiki hosted on Github.
=> Replacing old links to Selenium documentation with correct links

lib/transport/selenium3.js
This PR fixes #2464. All I'm doing is adding some checks to make sure that values are truthy before trying to reference a member on them.
=> Eliminate type errors due to bad BrowserStack response.

lib/api/element-commands/_waitFor.js, lib/element/command.js, test/src/api/commands/testWaitForElementVisible.js
Fixes https://github.com/nightwatchjs/nightwatch/issues/2194
When specifying a locator strategy in a `waitFor*` command, the locator strategy was not taken into account. This PR implements the `setStrategyFromArgs()` method for `WaitForElement` class and sets the locator strategy if the first 2 arguments are of string type.
=> Check for locator strategy in waitFor* commands

lib/api/element-commands/_baseElementCommand.js
This PR fixes #2530 by adding a single log in cases when element was not found running an element command, such as `.click()` or `.getText()`.
=> Fix #2530: Add logs for missing element when running .click()

lib/testsuite/index.js
- When running tests in multiple environments in parallel on a cloud testing platform (e.g. BrowserStack), the status of the test is not sent. Even if the test ran successfully or failed the status at the cloud testing platform is unmarked.
- Run a positive test using env browserstack.chrome, browserstack.firefox `npx nightwatch <test_file> --env browserstack.firefox,browserstack.chrome`
- After the test runs successfully you can observe the status of the test marked as `unmarked` on the BrowserStack dashboard.
- Running the test in multiple environments uses child processes and we need to update the status in the transport layer by calling `this.client.transport.testSuiteFinished(failures)` irrespective of whether it's a child process or not.
- So moved the lines …
=> update the status of testSuite in client transport

lib/reporter/global-reporter.js
Fixes #2728 
**Overview**
XML output files are not generated when running parallel tests on multiple browsers, because when we run concurrent tests, we only check the master process to push the results to the 'GlobalReporter', but in fact, the tests are spawn through the child process.
=> fix: xml output generation for parallel tests

lib/api/protocol/timeouts.js, lib/transport/selenium-webdriver/method-mappings.js
- refactored method mapping for timeouts.
- dropped the support of `type=page load` for timeout as it is not supported by selenium-webdriver
=> Method mapping for timeouts

lib/transport/factory.js, test/src/index/testCreateTransport.js
- refactor test cases to work with selenium-webdriver.
- refactor `/transport/factory.js` to support `didyoumean` in case of wrong browsername
- need to refactor test cases in transport for browserstack.
=> refactor transport testcases

lib/core/asynctree.js, test/sampletests/es6await/selenium/failures/verifyWithFailures.js, test/src/runner/testRunnerEs6Async.js
- remove rejection of node promise. It creates unhanded rejection error.
- fixes #2794
=> remove node promise rejection in case of error

lib/testsuite/index.js, lib/transport/browserstack.js, lib/utils/index.js, test/src/index/testCreateTransport.js
- send the reason of failure to BrowserStack transport.
- Before: 
-After:
=> send last error to browserstack transport reason

lib/transport/selenium-webdriver/method-mappings.js, test/src/api/protocol/testSetValue.js
The previous value is now when we use `setValue`
=> fix: value is not cleared before setting value

lib/http/request.js, lib/http/response.js, lib/index.js, test/src/index/testNightwatchIndex.js, test/src/index/testRequest.js, test/src/index/testRequestTimeout.js, test/src/index/testRunProtocolAction.js
- emit error even in `http/response.js`
- removed multiple emition of error even in `http/request.js`
- set default port as 4444
- refactored testcases in `src/index`
=> refactor-index-testcases

lib/api/_loaders/ensure.js, test/lib/fakedriver.js, test/lib/globals.js, test/src/api/protocol/testEnsure.js
- updated `ensure` loaders to support promises.
- added protocol tests for `ensure` element commands.
=> Ensure api tests

lib/http/request.js, lib/transport/selenium-webdriver/httpclient.js, test/src/service-builders/testFirefoxDriver.js
- update the port in `http.globalSettings` which can be used in making requests for commands that don't use selenium-webdriver and uses Nightwatch client instead.
- fixes #3054
=> update port in Http global settings from webdriver httpClient

lib/api/expect/cookie.js, lib/transport/selenium-webdriver/actions.js, lib/transport/selenium-webdriver/index.js, package-lock.json, package.json, test/lib/command-mocks.js, test/lib/mocks/mocks-jsonwire.yaml, test/lib/nocks.js, test/src/api/commands/element/testGetElementRect.js, test/src/api/commands/element/testGetElementSize.js, test/src/api/commands/element/testGetFirstElementChild.js, test/src/api/commands/element/testGetLastElementChild.js, test/src/api/commands/element/testGetLocation.js, test/src/api/commands/element/testGetLogTypes.js, test/src/api/commands/element/testGetNextSibling.js, test/src/api/commands/element/testGetPreviousSibling.js, test/src/api/commands/element/testHasDescendants.js, test/src/api/commands/element/testIsVisible.js, test/src/api/commands/element/testWaitForElementNotVisible.js, test/src/api/commands/element/testWaitForElementVisible.js, test/src/api/commands/logs/testIsLogAvailable.js, test/src/api/expect/testExpectCookie.js, test/src/api/expect/testExpectValue.js, test/src/api/expect/testExpectVisible.js, test/src/runner/testRunTestsuite.js, test/src/runner/testRunnerEs6Async.js, test/src/runner/testRunnerWithSeleniumWebdriver.js
checkResponse was deprecated in Selenium and has been removed. This PR moves to the method that was suggested.
=> Upgrade Selenium to 4.1.1

lib/runner/process-listener.js
=> Fix mocha wrong exitcode issue

cucumber-js/_setup_cucumber_runner.js, lib/index.js, lib/transport/selenium-webdriver/browserstack.js, test/extra/cucumber-config.js, test/src/runner/cucumber-integration/testCucumberWithBrowserstack.js
- extracted scenarios results in the `After` hook and send to BrowserStack.
- exposed `transport` from Nightwatch `createClient`.
- added tests for the change.
- fixes #3132
=> Fixed #3132 - Mark test scenarios passed/failed and send reason to Browserstack while using Cucumber as a test-runner

lib/runner/cli/cli.js, lib/runner/cli/nightwatch.conf.ejs, lib/transport/selenium-webdriver/browserstack.js, test/src/cli/testCliRunnerGenerate.js, test/src/index/transport/testBrowserstackTransport.js
BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY are the env variables specified in docs, check for these. Also accept buildName, local if sent inside 'bstack:options'
Added an issue here: https://github.com/nightwatchjs/nightwatch/issues/3149
=> fix: accept standard browserstack environment variables

lib/api/protocol/url.js
Setting [`discardStdin`](https://github.com/sindresorhus/ora/issues/209) to `false` resolves #3268 as the `stdin` stream is no longer paused. And not discarding the `stdin` stream does not create any issue as such and the spinner still works fine.
=> Set discardStdin to false while initializing ora.

lib/reporter/global-reporter.js, lib/reporter/reporters/html.js, lib/runner/test-runners/mocha.js, lib/settings/defaults.js, lib/settings/settings.js, test/lib/utils.js, test/src/cli/testCliRunner.js, test/src/cli/testCliRunnerMocha.js, test/src/runner/testRunnerHtmlOutput.js
- Add a flag to retain HTML report across test runs
- Default behaviour is not changed it generates different HTML reports if `retain_report` is set to true
- fixes #3307
=> retain html report

test/sampletests/withuncaughterrors/demoTestWithError.js, test/src/api/commands/client/testPause.js, test/src/runner/testRunnerUncaughtErrors.js
~Increased the time in assertions to give a good margin to the `pause()` command to complete.~
Removed the upper limit of time for pause command.
Tested on Windows machine by running the tests multiple times.
=> Fix cli failure on Windows due to pause() tests.

test/sampletests/es6await/selenium/failures/sampleWithFailures.js
Without this change, the success rate of the test is 1/5. With this, it's passing every time.
=> Fix cli failure on Windows related to Es6Async.

lib/api/expect/cookie.js, test/lib/nocks.js
- #3361 
- Array check was removed since the [getCookie function](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/lib/webdriver.js#L1831-L1853) in Selenium always returns the result as an object rather than an array (**Note** : _I also tested it on subdomains and paths to see if it produces an array value or not, but I always got an object instead of an array._ )
- Fixed `result.value.value` to `result.value` because `result.value.value` is returning `undefined` value
- Modified Nock's cookie response to fix the test-cases
=> Fix #3361 expect.cookie always returning undefined value

test/src/index/transport/testBrowserstackTransport.js
**The problem:** following error occurs after test execution completes, and assertions are not executed.
```
PUT https://api.browserstack.com:9999 /automate/sessions/1234567.json - ETIMEDOUT
Error: connect ETIMEDOUT 52.1.181.200:9999
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
```
=> Fix test for Browserstack Transport

lib/core/client.js, test/src/index/testMobileComponent.js
-  Replacing localhost with 10.0.2.2 in baseUrl for mobile component testing on mobile.
=> Component testing on android emulator 

lib/core/treenode.js, test/src/core/testTreeNode.js
Removes complete listener if error event occurs, and vice versa for complete event.
=> Fix#3387 Remove event listeners on command completion

lib/api/client-commands/pause.js, test/src/api/commands/client/testPause.js
=> Added a check for 0 ms in pause command

lib/runner/concurrency/index.js
Without the fix module names look like this when there are few modules in a folder
```bash
Running:  chrome: tests/duckDuckGo.js 
Running:  chrome: ecosia.js 
Running:  chrome: explore.js 
```
Should look like this:
```
Running:  chrome: tests/duckDuckGo.js 
Running:  chrome: tests/ecosia.js 
Running:  chrome: tests/explore.js 
```
=> fix module names for parallel runs

lib/utils/requireModule.js
* Fixes #3584.
When the [`requireModule()` utility function](https://github.com/nightwatchjs/nightwatch/blob/main/lib/utils/requireModule.js) determines that the given `fullpath` argument corresponds to an ECMAscript module, it tries to import the module as follows:
```js
import(fullpath)
```
Node.js' ESM loader requires that the given argument be a `file://` URL, but `fullpath` is instead an absolute path whose form varies by operating system:
| | *nix | Windows |
| --- | --- | --- |
| `fullpath` | `/foo/bar.js` | `c:/foo/bar.js` |
| Outcome | ✔️ Succeeds because the path can still be interpreted as a URL. | ❌ Fails because the path cannot be interpreted as a URL due to the leading drive letter. |
The error message on Windows:
``` …
```
=> Fix ESM imports on Windows

lib/http/http.js, lib/http/request.js, lib/transport/selenium-webdriver/browserstack/appAutomate.js, lib/transport/selenium-webdriver/browserstack/browserstack.js, lib/transport/selenium-webdriver/index.js, test/src/core/testCreateSession.js, test/src/index/testRequest.js
To test an app on BrowserStack app-automate, we first need to upload that application to BrowserStack using BrowserStack's REST API: https://www.browserstack.com/docs/app-automate/api-reference/appium/apps#upload-an-app
The upload can be done either from a public URL or using a file from the local filesystem. This PR allows users to set `appUploadPath` or `appUploadUrl` as desired capability if they wish to upload the app they wish to test to BrowserStack. 
Additionally, if they have already set `appium:app` desired capability to some BrowserStack URL (starts with `bs://`), it will be overwritten with the new URL. And if they have set `appium:app` to something else other than BrowserStack URL, that will be considered as the custom id while uploading the application, which then can be used …
=> Add support to upload app to app-automate.

lib/runner/test-runners/default.js, lib/testsuite/index.js, test/src/runner/testRunnerEndSessionOnFail.js
- avoid closing the session when `end_on_session_fail` is set to false
- added logic to avoid reusing sessions in case of failure when `end_on_session_fail` is enabled
- It would spawn a new session and reuse that if a failure is detected in the preceding test and will keep that session open.
- fixes #3574
=> avoid closing of session according to end_session_on_fail

lib/runner/concurrency/child-process.js
Remake of https://github.com/nightwatchjs/nightwatch/pull/3614 because the CLA Agreement gave me some trouble with my enterprise account.  Re-doing the work away from my enterprise account. 
After a discussion on the Discord Channel, it appears that it may be beneficial to the community to remove the Boxen Library from the Concurrent Test Output.
Discord Thread: https://discord.com/channels/618399631038218240/1073406595725275267/1073406595725275267
=> removed boxen from concurrent test runs

lib/element/appium-locator.js, lib/element/locator-factory.js, lib/element/locator.js, lib/element/strategy.js, lib/transport/selenium-webdriver/method-mappings.js, lib/utils/locatestrategy.js, test/apidemos/appium/appiumTest.js, test/src/apidemos/appium/testAppiumAPI.js
This PR adds support for missing Appium locate strategies used to locate elements in native apps.
=> Add support for Appium locate strategies.

lib/api/client-commands/registerBasicAuth.js
Based on this https://www.selenium.dev/blog/2021/a-tour-of-4-authentication/ This feature is currently implemented on top of Selenium 4’s CDP(Chrome DevTools Protocol) support, and so only works on those browser that support that protocol. That means it won't work in Safari.
And it's not going to solve the Safari basic auth issue in selenium. See https://www.browserstack.com/docs/automate/selenium/basic-http-authentication
=> api-docs: update registerBasicAuth

lib/transport/factory.js, lib/transport/selenium-webdriver/selenium.js, test/src/core/testCreateSession.js
This PR allows users to use any browser with BrowserStack, as well as while creating a session with Appium server.
This is because with BrowserStack, we can send any browser name and instead of returning an error it creates a session with Chrome browser as default. And with Appium server, accepted values of `browserName` depends on the driver being used and hence cannot be pre-defined.
With selenium server, because we use Selenium's `Builder` class which supports only a few browsers, it will throw an appropriate error for other unsupported browsers instead of just some random error.
=> Allow to use any browser with BrowserStack and Appium.

lib/core/queue.js, test/apidemos/custom-commands/testUsingAutoInvokeCommand.js, test/extra/commands/autoInvoke/customCommandInvoke.js, test/src/apidemos/custom-commands/testCustomCommandAutoInvoke.js
- avoid push command node marked with `autoInvoke` to command Queue
- fixes #3652
=> avoid pushing autoInvoked command nodes to command queue

lib/api/client-commands/cookies/delete.js, lib/api/client-commands/cookies/deleteAll.js, lib/api/client-commands/cookies/get.js, lib/api/client-commands/cookies/getAll.js, lib/api/client-commands/cookies/set.js, lib/api/client-commands/deleteCookies.js, lib/api/client-commands/getCookie.js, lib/api/client-commands/getCookies.js, lib/api/client-commands/setCookie.js, lib/api/expect/cookie.js, lib/api/protocol/cookie.js, lib/transport/selenium-webdriver/method-mappings.js, test/apidemos/cookies/cookieTests.js, test/apidemos/cookies/cookieTestsWithError.js, test/lib/command-mocks.js, test/src/api/commands/cookies/testCookie.js, test/src/api/commands/cookies/testCookies.js, test/src/api/commands/cookies/testCookiesErrors.js, test/src/apidemos/cookies/testCookieCommands.js
This PR moves all the cookie-related commands to `.cookies` namespace and deprecates the older commands.
New commands added:
- `.cookies.get()`
- `.cookies.getAll()`
- `.cookies.set()`
- `.cookies.delete()`
- `.cookies.deleteAll()`
Old commands deprecated:
- `.cookie()`
- `.getCookie()`
- `.getCookies()`
- `.setCookie()`
- `.deleteCookie()`
- `.deleteCookies()`
=> Move cookie-related commands to `.cookies` ns.

lib/api/web-element/commands/click.js, lib/api/web-element/commands/getShadowRoot.js, lib/api/web-element/scoped-element.js, lib/transport/selenium-webdriver/method-mappings.js, test/src/api/commands/element/testGetAttribute.js, test/src/api/commands/element/testGetAttributeW3c.js, test/src/api/expect/testExpectAttribute.js
This PR contains the following:
* Element action-commands like `click`, `clear`, etc. shouldn't return `ScopedWebElement` instance without await, as it is of no use. Additionally, when used with `await`, these commands should return the actual result (`null`) just like before, instead of returning `WebElement` of the element on which the command is performed.
* Get attribute related assertions (like `attributeEquals`) working with `WebElement` as well.
* Add a fix to `getShadowRoot` command, similar to `getFirstElementChild` and related commands.
=> More v3 fixes

test/src/api/commands/web-element/assert/testElementAssertions.js
* `present` assertion does not work.
* Failing `hasClass` and `hasAttribute` assertions does not fail the unit test, while they fail the actual e2e test.
=> Add tests for element assertions.

lib/utils/index.js, lib/utils/screenshots.js, package-lock.json, package.json, test/src/runner/testReporter.js, test/src/runner/testRunnerHtmlOutput.js, test/src/runner/testRunnerJsonOutput.js, test/src/runner/testRunnerJunitOutput.js
- remove `mkpath` as a dependency because it has not been updated and is causing issues while using a `strict` flag in the javascript module.
- There is been no new version published for 7 years now even after following up. Refer to this issue: https://github.com/jonvuri/mkpath/issues/6
=> remove mkpath as a dependency

lib/api/_loaders/element-global.js, lib/index.js
The removed block of code was overwriting the Proxy for `module.exports.element` defined at the end of `lib/index.js` file.
We can safely remove this block of code as right now this anyway does not work for normal Nightwatch tests (`client` should be set to an instance of `NightwatchClient` and not `NightwatchAPI`), but only works for programmatic API I assume. And for programmatic API, we are anyways overwriting it [here](https://github.com/nightwatchjs/nightwatch/blob/main/lib/index.js#L114-L119).
So, removing this code would:
* Have no side-effects on normal Nightwtach tests as it didn't work earlier.
* Have no side-effects on programmatic api as we are still overwriting `Nightwatch.element` as linked above.
=> Make new element api available as named export.

lib/api/web-element/commands/findByLabelText.js, lib/api/web-element/element-locator.js, lib/api/web-element/scoped-element.js, lib/transport/selenium-webdriver/method-mappings.js, test/src/api/commands/web-element/testFindByLabelText.js
Refactored the implementation to rely less on the queue. There are some caveats:
- taken into account the `timeout` and `retryInterval` only for the initial  label element lookup and the following input element lookup will not be retried (to do so would add significantly more complexity and I'm not sure it is needed; in case it is needed we will revisit it later)
- `findByDeepNesting` and `findByAriaLabel` will be queued with the command name as `find`
- normally all these 3 requests could be parallelised and we can use `Promise.any()` instead but our existing queue implementation does not support executing nodes in parallel nor does it support cancellation of nodes; the straightforward solution to this is to not use the queue, which means not using the `.find()`; however, not using …
=> fixed issues with findByLabelText

lib/api/web-element/element-locator.js
This PR fixes the issue with `pageObject.element('@someElement')`. The problem was that the `condition` should be an instance of `By` or `RelativeBy` as it is directly passed to Selenium methods, but it was an instance of `Element` in case of page object.
=> Fix element api support in POM.

lib/runner/concurrency/worker-process.js, test/src/runner/cli/testCliRunnerParallel.js
Fixes: https://github.com/nightwatchjs/nightwatch/issues/3686
Fixes: https://github.com/nightwatchjs/nightwatch/issues/3687
=> fix: env is not passed to worker threads

lib/api/assertions/hasAttribute.js, test/src/api/assertions/testHasAttribute.js
- #3608 
As discussed with @AutomatedTester, removing the uses for multiple attributes as the webdriver's [get element attribute API](https://www.w3.org/TR/webdriver/#get-element-attribute) returns only one attribute value.
=> Added a fix for assert.hasAttribute

lib/runner/process-listener.js
While running unit tests on nightwatch, a lot of times the process exits abruptly without showing any errors. This happens mostly due to uncaught exceptions within nightwatch which kiss the process. 
I am updating the log line here so that such uncaught exceptions gets printed regardless of logger settings.
=> Always throw uncaught exceptions

test/src/cli/testServiceCreationFromCli.js, test/src/core/testPageObjectWaitForElementNotPresent.js
- Fixed a test of `waitForElementNotPresent`
- Removed the done() callback to end the test after an assertion. Because if the assertion fails, done() will never be called.
- #3580
=> Test fix: waitForElementNotPresent

lib/api/web-element/factory.js, lib/api/web-element/waitUntil.js, lib/transport/selenium-webdriver/method-mappings.js, test/apidemos/web-elements/waitUntilFailureTest.js, test/apidemos/web-elements/waitUntilTest.js, test/lib/command-mocks.js, test/src/apidemos/web-elements/testWaitUntil.js
- added `waitUntil` module to element command
```js
element.find(<selector>).waitUntil(<action>).sendKeys('Nightwatch');
```
**OR** 
```js
element.find(<selector>).waitUntil({action, timeout, retryInterval, abortOnFailure, message});
```
action could be: `enabled` `visible` `disabled` `selected` `not.selected` `not.visible` `not.enabled`
=> added waitUntil module to element apis

lib/reporter/results.js, lib/testsuite/index.js, test/src/runner/testReporter.js
The retry data is not getting populated in global reporter when tests get failed. We push only the latest data but loose the previous retries data for that particular test.
Suppose we have a test which will have following data inside reporter:
```
"Demo test ecosia.org ": {
"time": 0,     
"assertions": [],
"commands": [ ],
"passed": 0,
"errors": 0,
"failed": 0,
"skipped": 0,
"tests": 0,
"status": "pass"
},
```
Previously we are not pushing the retried data anywhere. But now I added a key `retryTestData` and pushed all retried data inside it and keeps the latest data as it is.
```
"Demo test ecosia.org": {
"time": 0,                     
"assertions": [],          
"commands": [ ],       
"passed": 0,                     ===>   latest data
"errors": 0,                    
"failed": 0 …
```
=> feat/retry-data: Added retry test data to global reporter

types/assertions.d.ts, types/custom-assertion.d.ts, types/index.d.ts, types/utils.d.ts
This PR adds types for the modified non-element API and new namespaced API.
Because the return type of all the namespaced commands will differ based on whether they are called as `browser.namespace.commandName()`, or directly as `namespace.commandName()` by importing the namespace from `'nightwatch'` first, a `ReturnType` generic is used to decide that return type.
* In normal cases (when commands are called as `browser.namespace.commandName()`), `ReturnType` is set to `NightwatchAPI` so that the commands continue to work as before.
* In cases where the namespace is imported from 'nightwatch', `ReturnType` will be `unknown` (its default type) and hence the commands will return `this` (the namespace itself).
=> Add types for modified non-element API.

lib/reporter/base-reporter.js, lib/reporter/index.js, lib/reporter/reporters/html.js, lib/reporter/reporters/junit.xml.ejs, lib/reporter/results.js, lib/reporter/summary.js, lib/testsuite/context.js, lib/testsuite/index.js, test/extra/reportObject.js, test/src/runner/testRunnerJunitOutput.js
The skipped tests that were marked by the user were not getting logged.
The reporter now differentiates between tests that were skipped at runtime and those skipped by the user, using `skippedAtRuntime` and `skippedByUser` properties respectively, instead of just `skipped`.
**Note** : _This change should also be incorporated in the HTML reporter._
=> Skipped tests have categorized as either user-marked or runtime-failed

.github/workflows/types-checked.yml, .github/workflows/types-checker.yml, .husky/pre-commit, package-lock.json, package.json
To maintain consistency in Nightwatch contributions, this PR now requires contributors to update the "types" when submitting a pull request through Github Action. If the "types" are not found in the PR, Github Action will provide a comment as a reminder. Once the user has added the necessary types, Github Bot will update the comment accordingly.
I've included "husky" as a pre-commit tool to guarantee that our code adheres to eslint standards and maintains quality.
We need to update Action Permission for this group
=> chore: Add Github Action and husky

types/index.d.ts, types/page-object.d.ts, types/tests/index.test-d.ts, types/utils.d.ts
The issue with the types of page objects was that some new generics were added in `EnhancedPageObjects` interface in between the generics that were already present, due to which the interface was no longer backwards compatible. This PR fixes the issue by moving the newly added generics to the end of the interface.
* First, create a page object, along with an interface for the created page:
```ts
// nightwatch/page-objects/googlePage.ts
import { EnhancedPageObject, PageObjectModel } from 'nightwatch';
const googleCommands = {
clickSearch(this: GooglePage) {
return this.waitForElementVisible('@submit', 10000)
.click('@submit')
.waitForElementNotPresent('@submit');
},
};
const googlePage: PageObjectModel = {
url: 'http://www.google.com',
commands: [googleCommands],
elements: {
searchBar: { …
```
=> Fix types for page objects.

lib/transport/selenium-webdriver/service-builders/chrome.js, test/src/service-builders/testChromeDriver.js, test/src/utils/testStackTrace.js
Earlier, we were making it mandatory for chromedriver to always emit logs in `--verbose` mode, so passing `--silent` or `--log-level=OFF` cli_args did not work and threw the following error:
```
Only one of --log-level, --verbose, or --silent is allowed.
Unable to initialize logging. Exiting...
```
=> Allow users to disable chromedriver logs in Nightwatch.

lib/api/web-element/element-locator.js
Right now, the following code doesn't work as expected (always returns the first element):
```js
const elem = await browser.element({selector: '.shelf-item', index: 12});
```
This is because the `.element()` command accepts an `index` property for mentioning the index of the element to return, but the code was only checking for `__index` property, which does not exist here.
But the `__index` property is also important to check because in case an instance of `Element` class is passed to `browser.element()` command, `obj.hasOwnProperty('index')` would fail for it because `index` is not a direct property of `Element` but only a getter for `__index` property. So, both are needed to be checked.
=> Fix issue with locating nth element in new element API.

examples/tests/duckDuckGo.js
'duckDuckGo.js' test was not working earlier. 
I have used better selector to run the example test so it doesn't fail whenever changes happen in the 'DuckDuckGo' website.
=> Fix 'duckDuckGo.js' example test.

types/globals.d.ts
Fixes #3757.
Changing `unknown` to `any` would allow users to access nested properties in Nightwatch globals without having to do too much work.
* The only downside of this approach is that now users could access `browser.globals.levelOne.levelTwo.someVariable` in TS even if that variable does not exist. But it's the only easy way to allow users to access nested variables, all other approaches (some of which are listed below) would be too much work.
* It should be noted that `browser.globals.someVariable` would not give error for both `unknown` and `any` if `someVariable` does not exist. So, the only change is with the nested variables.
* One (and only correct) alternative solution for this is to extend `NightwatchGlobals` interface to include all the custom-defined global properties by …
=> Allow access of nested globals properties.

.github/workflows/nightly.yml
This would allow us to release a certain branch or commit in Nightwatch as a pre-release so that users can try it out before it goes into the main release.
It can be triggered manually, where it asks for the Nightly version name/number and the Git ref to release, and creates a pre-release based on the inputs.
Sample run: https://github.com/garg3133/nightwatch/actions/runs/5411304762/jobs/9833867052
Sample release: https://github.com/garg3133/nightwatch/releases
=> Add manually triggered Nightly release workflow.

types/index.d.ts
Added Firefox namespace commands:
1. `getContext()`
2. `setContext()`
3. `installAddon()`
4. `uninstallAddon()`
=> Add types for Firefox namespace commands

lib/api/web-element/commands/takeScreenshot.js, test/src/api/commands/web-element/testTakeScreenshot.js, types/tests/webElement.test-d.ts, types/web-element.d.ts
Also, `takeScreenshot` command does not take any argument: https://github.com/SeleniumHQ/selenium/blob/4d70bd80f40592c12170ca8382d54064278add6f/javascript/node/selenium-webdriver/lib/webdriver.js#L3048-L3052
=> Fix takeScreenshot command not returning anything.

lib/api/_loaders/_base-loader.js, lib/api/client-commands/document/source.js, lib/api/client-commands/window/open.js, lib/api/client-commands/window/setSize.js, lib/api/client-commands/window/switchTo.js, lib/api/element-commands/getAttribute.js, lib/api/element-commands/setPassword.js, lib/api/protocol/execute.js, lib/api/protocol/executeAsyncScript.js, lib/api/protocol/switchToWindow.js, test/apidemos/custom-commands/testNamespacedAliases.js, test/apidemos/namespaced-api/namespacedApiTest.js, test/extra/commands/customExecute.js, test/extra/commands/customPauseWithNamespacedAlias.js, test/src/apidemos/custom-commands/testCustomPauseWithNamespacedAlias.js, test/src/apidemos/namespaced-api/testNamespacedApi.js
This PR adds support for adding namespaced aliases to Nightwatch commands. This would allow us to make a particular command available on multiple namespaces without the need to duplicate the file at multiple places.
This can be achieved by adding a `namespacedAliases` static get method to any command file. The aliases returned by the method should be absolute (how it will be used on the main `browser` object) and should end with the command name).
Having the aliases as absolute is necessary so that we can make a command having a namespace already, be available on the main `browser` object. For example, making `browser.appium.hideKeyboard()` command available as `browser.hideAppiumKeyboard()` as well, instead of the other way around.
Inside `lib/api/protocol/navigateTo.js` command, add the …
=> Add support for namespaced aliases.

package-lock.json, package.json
This fixes an issue with nightwatch-axe-verbose that allows Nightwatch to work with Yarn > 1 https://github.com/reallymello/nightwatch-axe-verbose/pull/14
=> chore(deps): update dependency nightwatch-axe-verbose to ^2.2.2

package-lock.json, package.json
**Why jsdom is updated?**
There were two dependency vulnerabilities, `w3c-hr-time` and `tough-cookie`, which are dependent on the dependency `jsdom` hence in order to fix this issue `jsdom` upgrade was considered.
**Why jsdom is updated to v21.1.2?**
v21.1.2 is the highest version that won't lead to any breaking change. Updating further, Node.js v16 will be the minimum supported version.
**Why npm audit fix is run?**
In order to fix the vulnerability `word-wrap` which was of moderate severity, `npm audit fix` command was run.
=> Update jsdom to v21.1.2 and npm audit fix.

lib/runner/test-runners/cucumber.js, test/src/runner/cucumber-integration/testCliArgs.js
=> fix(cucumber-runner): allow esm imports (#3805)

lib/reporter/index.js, lib/runner/concurrency/task.js, lib/runner/concurrency/worker-task.js, lib/testsuite/index.js, test/apidemos/custom-commands-parallel/testUsingES6AsyncCustomCommands.js, test/extra/commands/other/otherCommand.js, test/extra/parallelism-customCommandsSync.json, test/src/apidemos/custom-commands/testCustomCommandSync.js
Fixes: #3786.
The issue here was that custom commands many times return an instance of `NightwatchAPI` instead of the actual command result. Due to this, when destructuring `status` from `result`, `status` was getting assigned the definition of `.status()` (a function) command instead of the status of the command run (a number).
Now, while being in parallel mode, reports from all test runs are sent to a common port (see [here](https://github.com/nightwatchjs/nightwatch/blob/90165d5393c7a74c0670ffcfd731b62e506ac9bb/lib/testsuite/index.js#L671-L674)), but the `postMessage` method does not work with functions, and so it was failing for tests containing custom commands.
Due to this, while the test with custom commands was running fine, it was not getting reported on the terminal as well as in …
=> Fix sync tests getting skipped in parallel mode.

package-lock.json, package.json
**Why uninstalled coveralls?**
Two packages, `tough-cookie` and `request`, had moderate vulnerabilities (with no fix available). Both packages were dependent on the dev-dependency `coveralls` hence it was deleted to fix the vulnerabilities.
(Also, coveralls is no longer used in Nightwatch.)
**Command used:** `npm un -D coveralls`
=> Uninstall Coveralls

package-lock.json, package.json
Affected version of semver 7.3.5, which was creating a vulnerability, is updated to the patched version 7.5.2
Fixes: #3827
=> updated semver to v7.5.2

lib/runner/concurrency/index.js, lib/runner/concurrency/worker-task.js, test/src/runner/cli/testCliRunnerParallel.js
- add error handling to worker threads (non-test execution error)
- return the correct exit code on execution failure
- fixes https://github.com/nightwatchjs/nightwatch/issues/3787
- fixes https://github.com/nightwatchjs/nightwatch/issues/3804
- fixes #3833
=> add error handling for worker threads

lib/runner/folder-walk.js
The error originates in the function `applyTagFilter` which lies in `folder-walk.js`
The cause of the error is that when any folder that is defined in `src_folders` in the file `nightwatch.conf.js`, is empty, the `list` parameter of the function `applyTagFilter` goes undefined. When the function executes, it uses the Array property `.map()` on `list` parameter which is undefined and hence the error.
To fix this, an if condition is added to the top of the function body which returns the function if the parameter `list` doesn't qualify as an array.
Fixes: #3823
=> Fixed the issue regarding error if a folder defined in `src_folders` is empty when using tags

lib/core/client.js, test/src/index/transport/testEdgeOptions.js
=> Fix: .registerBasicAuth() not working in Edge browser #3848

package.json, test/src/utils/__data__/meaning-of-life.js, test/src/utils/__data__/meaning-of-life.mjs, test/src/utils/testRequireModule.js, tsconfig.json
=> fix: es6 module import

package-lock.json, package.json
closes #3506
I think maybe the https://github.com/mochajs/mocha/pull/4861 PR could cause breaking changes, but I did not find any code that uses the old `delay` constructor option
=> chore: bump mocha 9.2.2 => 10.2.0

lib/settings/settings.js
- support `GITHUB_ACTIONS` for enabling colors in CLI
- fixes #3601
=> add GitHub Actions in the list of supporting colors

lib/api/element-commands/waitForElementVisible.js
- fix the description of `abortOnFailure` in `waitForElementVisible` command.
=> Update the description of abortOnFailure for waitForElementVisible.js

lib/runner/concurrency/index.js, test/src/cli/testParallelExecution.js
-  remove the upper bound for a number of worker threads.
- fixes #3928
=> remove upper bound for number of worker threads

examples/tests/shadowRootExample.js, lib/api/element-commands/getShadowRoot.js, lib/api/web-element/commands/getShadowRoot.js, lib/transport/selenium-webdriver/method-mappings.js, test/src/api/commands/web-element/testGetShadowRoot.js
Earlier, to get the shadow root of an element, we were executing a script in the browser which didn't work for Firefox due to some serialization issues. But now Selenium provides a `getShadowRoot()` method on `WebElement`, which can be used to reliably get the shadow root of an element across all browsers (as it hits the `element/{element id}/shadow` endpoint defined in the webdriver spec to get the shadow root).
Fixes: #3966
=> Fix shadow root not working on Firefox.

lib/runner/cli/cli.js, lib/utils/index.js
Fixes: #3959.
Apparently, `ts-node` does not work with `import()` calls, even when its `esm` config is set to `true`. So, this PR sets ts-node to compile and execute all `.ts` files as CommonJS, so that they can be imported using the trivial `require()` calls only, even in ESM projects, instead of having to use the `import()` call. But for importing JS files in ESM projects, `import()` will be used as before.
More details on the added config: https://www.npmjs.com/package/ts-node#module-type-overrides
=> Fix TS tests not working in ESM project.

lib/utils/analytics.js
This was happening because the `https` library now creates connections to be `keep-alive` by default ([related PR](https://github.com/nodejs/node/pull/46331)), which stays open until the response is read completely (https://github.com/nodejs/node/issues/50188#issuecomment-1766866864).
So, this PR fixes the issue by reading the response data.
Another fix was to set the `Connection` header to `'close'` (https://github.com/nodejs/node/issues/50188#issuecomment-1765143646), but I think the fix in this PR is the correct one.
=> Fix process stalling for 4 mins after test run in Node v20+.

lib/api/element-commands/_waitForDisplayed.js, test/src/api/commands/element/testWaitForElementVisible.js
Fixes part of: #3639.
After this PR, waitFor commands should also retry fetching stale elements again.
=> Fix waitFor commands not retrying for stale elements.

package-lock.json, package.json
Update `nightwatch-axe-verbose` plugin to the latest version to include the changes done in https://github.com/reallymello/nightwatch-axe-verbose/pull/17, which makes the `.axeRun()` command much more powerful.
=> Update nightwatch-axe-verbose dependency

types/index.d.ts, types/tests/elementCommands.test-d.ts
Fixes: #3981
Earlier, the typings for the waitFor commands were very restrictive due to which the formats which worked in JS were not working in TS.
This PR makes the types for the waitFor commands lenient so that everything that works in JS continues to work in TS, but at the added expense of not at all strict typings which could be error-prone for users (though the argument names have been constructed in a way to reduce this).
Other solution to this would have been to create an overload corresponding to every way the command can be used, but that would have led to way too many overloads for each waitFor command and would have been hard to manage.
=> Add exhaustive types for waitFor commands.

lib/http/request.js, lib/transport/selenium-webdriver/browserstack/browserstack.js, test/src/core/testCreateSession.js, test/src/index/transport/testBrowserstackTransport.js, test/src/runner/testRunBrowserstackTransport.js
Fixes: #3998 
This PR does the following:
* If the status of a test is already found to be set in BrowserStack, it does not overwrite the status.
* Only request for builds currently running while trying to get the build id (otherwise if there are too many builds, the build used in the test run is never returned by BrowserStack, due to which the build id is set to `undefined`).
=> Fix Nightwatch overwriting test status set by user.

lib/api/client-commands/axeInject.js, lib/api/client-commands/axeRun.js, types/index.d.ts, types/tests/index.test-d.ts
This PR updates the JSDoc/TSDoc and types for the axe commands, after the recent update to `nightwatch-axe-verbose@2.3.0`.
=> Update docs and types for axe commands.

lib/core/client.js, lib/transport/selenium-webdriver/index.js, lib/transport/selenium-webdriver/method-mappings.js, test/lib/command-mocks.js, test/src/apidemos/cdp/testCdpCommands.js
The CDP connections are currently reset after a session has finished, but this doesn't always work, like in the case of Selenium, which has its own implementation of `this.transport.sessionFinished` and hence `cdp.resetConnection()` is never called.
So, instead of resetting the CDP connection after a session has finished, this PR moves that function call to when a new session is created, which is much more reliable, as whenever we get a new browser session, that's when we'd need a new CDP connection for that session.
Also, even in a single browser session, calling `.registerBasicAuth()` requires a new CDP connection to be created every time, otherwise the basic auth credentials are never registered. This PR fixes that as well.
Fixes: #3990.
=> Tweak when CDP connection is reset.

lib/api/web-element/scoped-element.js, lib/api/web-element/scoped-elements.js, test/src/api/commands/web-element/testShadowFind.js, test/src/api/commands/web-element/testShadowFindAll.js
Instead of calling `.findElements()` directly on `parentElement.webElement` (which is always a `WebElementPromise` due to which `.findElement()` method on it will always hit `/elements/:elementId/elements` endpoint), we first resolve `parentElement.webElement` promise in this PR to get a corresponding instance of `WebElement` or `ShadowRoot` and then apply `.findElements()` on top of the actual result.
Fixes: #3989
=> Fix element lookup with reference to a shadow root.

lib/api/_loaders/chrome.js, types/index.d.ts
Added Chrome namespace commands:
1. `launchApp()`
2. `getNetworkConditions()`
3. `setNetworkConditions()`
4. `sendDevToolsCommand()`
5. `sendAndGetDevToolsCommand()`
6. `setPermission()`
7. `setDownloadPath()`
8. `getCastSinks()`
9. `setCastSinkToUse()`
10. `startCasttabMirroring()`
11. `getCastIssueMessage()`
12. `stopCasting()`
=> Add types for `chrome` namespace commands

lib/transport/selenium-webdriver/service-builders/base-service.js
Right now, if we try to exit Nightwatch by pressing `Ctrl+C`, we get an `uncaughtException` error. This happens because starting with Node 16, a signal of `string` type (i.e. `SIGINT`) is emitted on pressing `Ctrl+C` instead of `number` type, but `process.exit()` still accepts a code of  `number` type as the first argument.
This PR fixes this by always exiting the process with code `0` in case a `SIGINT` signal is encountered. (In Node 14 also, the process used to exit with code `0` upon pressing `Ctrl+C`.)
=> Fix error while exiting Nightwatch using Ctrl+C.

package-lock.json, package.json
Updating Piscina dependency to the latest version (`v4.3.1`) partially solves issue #4009 in that the main process no longer exits completely without showing any error in case of `uncaughtException` or `unhandledRejection` in one of the worker threads. Instead, any such error in worker threads is handled properly now, thanks to https://github.com/piscinajs/piscina/pull/361, and the error message appears in the console output of the affected test suites.
But there are still two issues remaining to be resolved for such cases:
* In case of an `unhandledRejection` or `uncaughtException`, the browser session is not closed properly and the browser window remains open while the test run exits. This happens in both serial and parallel mode of execution.
* While the process does not exit now in …
=> deps: Update `piscina` dependency to `v4.3.1`.

lib/runner/test-runners/cucumber/nightwatch-format.js
Send a `POST_SESSION_EVENT` event to parent worker with capabilities as soon as a session is created in worker thread when using Cucumber with `NightwatchEventHub` enabled (used for Test Observability).
=> Send `POST_SESSION_EVENT` with capabilities on session creation.

lib/api/protocol/appium/resetApp.js, lib/transport/selenium-webdriver/method-mappings.js, test/apidemos/appium/appiumTest.js, test/src/api/protocol/testResetApp.js, types/index.d.ts, types/tests/appiumCommands.test-d.ts
=> Add appium reset command

lib/reporter/global-reporter.js, lib/runner/test-runners/cucumber.js, lib/runner/test-runners/cucumber/_setup_cucumber_runner.js
Currently, the HTML reporter is not supported in Cucumber, but still the console logs say that an HTML report has been created for the test, leading to confusion for users since the created HTML reporter does not work in actual.
=> Disable HTML reporter in Cucumber.

lib/api/web-element/commands/isSelected.js, test/src/api/commands/web-element/testIsSelected.js, types/tests/webElement.test-d.ts, types/web-element.d.ts
=> Add missing `isSelected` command to new Element API.

README.md
This pr removes the unnecessary dollar symbol while copying the command
=> Refactor commands in README.

lib/api/web-element/scoped-element.js, test/src/api/commands/web-element/testIsVisible.js, types/tests/webElement.test-d.ts, types/web-element.d.ts
=> Added `isDisplayed()` as alias to `isVisible()`

lib/runner/cli/cli.js, lib/runner/test-runners/cucumber.js, test/cucumber-integration-tests/testCucumberTestsInParallel.js, test/extra/cucumber-config-parallel.js
=> allow parallel envs with cucumber

lib/api/web-element/commands/getRect.js, lib/api/web-element/scoped-element.js, test/src/api/commands/web-element/testGetRect.js, types/tests/webElement.test-d.ts, types/web-element.d.ts
Adds one of the alias mentioned in #3901 
=> Add `rect()` as alias for `getRect()` command.

lib/api/_loaders/_command-loader.js, lib/api/protocol/waitUntil.js, lib/core/asynctree.js
WaitUntil was getting prematurely resolved when used with async await. That is because inside the command queue tree, whenever child nodes are resolved, the parent node is also automatically called to be resolved which was causing pre mature resolution of waitUntil.
=> Fix `waitUntil` not working with async/await.

lib/api/_loaders/_command-loader.js, lib/api/protocol/waitUntil.js, lib/core/asynctree.js
Test case was not aborting when waitUntil was throwing error. The reason for the same is that whenever waitUntil throws error, the resolveNode method inside asyncTree.js just resolves the waitUntil node and thus the execution moves forward by adding new nodes and continuing the execution. To fix this, we need to reject node in case there's an error thrown thus we have introduced a flag which would help in knowing if we want to resolve the node or reject it.
=> Fix bug that aborts test when waitUntil throws error. #4157

lib/api/client-commands/debug.js, lib/api/client-commands/pause.js, lib/core/asynctree.js
Debug command similar to WaitUntil was getting prematurely resolved when used with async await. That is because inside the command queue tree, whenever child nodes are resolved, the parent node is also automatically called to be resolved which was causing pre mature resolution of debug.
=> Fix `debug()` allowing only one command run in async/await mode.

lib/api/web-element/commands/getAriaRole.js, lib/api/web-element/scoped-element.js, test/src/api/commands/web-element/testGetAriaRole.js, types/tests/webElement.test-d.ts, types/web-element.d.ts
Adds the `ariaRole()` alias for `getAriaRole()` as mentioned in #3901. 
Running an example test: 
=> Add `ariaRole()` as alias for `getAriaRole()`

lib/utils/mobile.js
Fix the command to run during iOS errors.
=> Fix help messages for iOS errors.

lib/api/web-element/commands/getAccessibleName.js, lib/api/web-element/scoped-element.js, test/src/api/commands/web-element/testGetAccessibleName.js, types/tests/webElement.test-d.ts, types/web-element.d.ts
fixes #4177  
- [ . ] Before marking your PR for review, please test and verify your changes by making appropriate modifications to any of the Nightwatch example tests (present in `examples/tests` directory of the project) and running them. `ecosia.js` and `duckDuckGo.js` are good examples to work with.
- [ . ] Create a new branch from master (e.g. `features/my-new-feature` or `issue/123-my-bugfix`);
- [ . ] If you're fixing a bug also create an issue if one doesn't exist yet;
=> Feat: Added `.accessibleName()` as an alias for `.getAccessibleName()`.

lib/transport/selenium-webdriver/method-mappings.js, test/src/api/commands/element/testClearValue.js, test/src/api/commands/web-element/testClear.js, test/src/api/commands/web-element/testSetValue.js, test/src/api/protocol/testElementCommands.js
Add a fallback for `clearValue` command where Nightwatch will now try to delete the text in an input field by sending backspaces if the text is not deleted by the clear command directly.
This fallback will also work for commands like `setValue`, `updateValue`, etc. which clears the text before entering new text.
=> issue #4028 fix : added fallback for clearValue command

lib/api/web-element/commands/getCssProperty.js, lib/api/web-element/scoped-element.js, test/src/api/commands/web-element/testGetCssProperty.js, types/tests/webElement.test-d.ts, types/web-element.d.ts
fixes #4167 
- [.] Before marking your PR for review, please test and verify your changes by making appropriate modifications to any of the Nightwatch example tests (present in `examples/tests` directory of the project) and running them. `ecosia.js` and `duckDuckGo.js` are good examples to work with.
- [.] Create a new branch from master (e.g. `features/my-new-feature` or `issue/123-my-bugfix`);
- [.] If you're fixing a bug also create an issue if one doesn't exist yet;
=> Feat: added `.css()` and `.getCssValue()` as an  alias for `.getCssProperty()`

lib/api/web-element/scoped-element.js, lib/transport/errors/index.js
Fixes: #4078 
Right now, whenever the new Element API is unable to find an element, it throws a very generic `Error`. Instead, it should throw a `NoSuchElementError` with proper information and help text with the error message.
=> Use `NoSuchElementError` when element not found in new Element API.

test/src/core/testPageObjectCommands.js
=> Update Page Object tests to make sure invalid Page Objects elements are handled

lib/reporter/index.js, test/src/runner/testReporter.js
Right now, if the command arg is of type object, it gets stringified as '[object Object]' in the reporter.
This PR fixes this by stringifying the args correctly using `JSON.stringify`.
=> Fix command args showing as '[object Object]' in reporter.

lib/api/element-commands/_waitFor.js
Right now, the `waitFor` commands (like `waitForElementVisible`) when used with `async/await` syntax do not abort the test on failure, even when `abortOnFailure` is set to `true`.
This PR fixes that by rejecting the command node upon failure when `abortOnFailure` is set to `true`, and thus aborting the test.
The implementation around this was merged recently in #4161.
=> Fix test not aborting when waitFor commands used with async/await.

package-lock.json, package.json
PR to update mocha version to remove [CVE-2022-3517](https://nvd.nist.gov/vuln/detail/CVE-2022-3517) found in the minimatch package that's a dependency of mocha <= 10.2.0.
Tests passed, assuming this one didn't just due to my local env, looks like just a few `__` are missing.
=> chore: updating mocha from 10.2.0 -> 10.3.0 to remove CVE-2022-3517

lib/transport/selenium-webdriver/options.js, package-lock.json, package.json, test/src/core/testCreateSession.js, test/src/index/transport/testChromeOptions.js, test/src/index/transport/testEdgeOptions.js, test/src/index/transport/testFirefoxOptions.js
`.headless()` method was [removed](https://github.com/SeleniumHQ/selenium/commit/5a97adf9864a346fdd8914cdb1b601c05dd837ac) in selenium-webdriver v4.17.0, so this PR handles that as well.
=> Bump selenium-webdriver to 4.20.0

lib/runner/test-runners/cucumber/_setup_cucumber_runner.js
Fixes: #3332.
Right now, even if the session is already closed inside a test case, Nightwatch still tries to close the session again in the `After` hook of Cucumber, resulting in an error.
With this PR, the session will only be closed in the `After` hook if it is not closed already.
=> Fix error in Cucumber when session is closed in a test case itself.

lib/api/client-commands/pause.js
This PR allows users to enter the DEBUG mode directly from the `.pause()` command by pressing the key `d`.
=> Allow to enter the DEBUG mode from the pause command.

examples/tests/selectElement.js
=> Fix selectElement example test.

types/index.d.ts, types/tests/webElement.test-d.ts, types/tests/webdriverProtocolCommands.test-d.ts
A few Appium-specific locate strategies have been missing from the types.
=> Add types for Appium-specific locate strategies.

lib/reporter/reporters/html.js
Currently, the text present inside the `describe` block in a test suite is not displayed anywhere in the HTML report, while the test suites should be majorly identified by this text only.
This PR fixes that by adding the `describe` name as a prefix in the left-side bar of the HTML report.
This is how it looks now:
compared to this before:
=> Display `describe` name in HTML report.

lib/api/web-element/scoped-element.js, lib/reporter/index.js, lib/reporter/results.js, lib/settings/defaults.js
Currently, the result values for the Nightwatch commands are not saved in the JSON report, only the result status is saved.
This PR allows users to save the command result values as well in the JSON report by setting the `save_command_result_value` config to `true` in the Nightwatch configuration file.
For large result values, a new file is created to put the result value and the path of that file is saved in the JSON report instead of the actual value.
cc: @sauravdas1997
=> Save command result values in Json Report.

lib/index.js
This PR exposes a few internal modules like `HttpRequest` and `cdp` as `utils` so that these modules can be imported and used directly inside test suites.
`HttpRequest` module is useful for modifying the settings of HTTP requests as and when required. For example, we can modify the HTTP timeout and retry attempts for a particular command by calling the `updateGlobalSettings` static method just before that command:
```js
HttpRequest.updateGlobalSettings({timeout: 10000, retry_attempts: 5});
```
Note: The above command would change the `HttpRequest` settings globally for the entirety of the test run. It should ideally be reset back to the original settings once the requirement is over.
Note 2: The initial values of `timeout` and `retry_attempts` can be set using the `timeout_options` …
=> Expose HttpRequest and cdp modules as utils.

examples/tests/staleElementReferenceError.js, lib/element/command.js, lib/transport/selenium-webdriver/actions.js, test/src/api/commands/element/testClickAndHold.js, test/src/api/commands/element/testDoubleClick.js, test/src/api/commands/element/testDragAndDrop.js, test/src/api/commands/element/testMoveToElement.js, test/src/api/commands/element/testRightClick.js
Fixes #4184
Adds selector and error line with proper formatting for "StaleElementReferenceError" and other errors that might occur when working with elements.
Since this updates the logs displayed, adding a test for it is hard. Instead, the PR adds an example to showcase the fix.
The changes now display the logs as follows:
=> Add selector and error line for "staleElementReferenceError"

lib/api/web-element/scoped-element.js
Fixes: #4079 
Fixes: https://github.com/dikwickley/gsoc24/issues/1
Solves the third point from this comment (https://github.com/nightwatchjs/nightwatch/issues/3991#issuecomment-1969444042)
> Further chained .find() commands should not throw the Timeout or any other error again. Ex. in browser.element('.invalid-selector').find('selector').getText();, there should only be one error due to browser.element()  and .find() should not throw an error again (suppress the error for it).
=> Suppressing error for further chained `.find()` commands

lib/api/protocol/frame.js
When the `.frame()` command is used with `await` (as shown below), the command promise resolves early before the command can even find the target frame element. Due to this, the subsequent Nightwatch commands start running parallelly with the `.frame()` command.
```js
await browser.frame('frame_a_simple_iframe');
await browser.waitForElementVisible('.example');
```
This PR solves this issue by ensuring that the `frame()` command promise is only resolved once the command has completed its execution so that the subsequent commands only run after that.
=> fix: frame command overlapping with subsequent NW commands.

lib/api/web-element/assert/element-assertions.js, lib/api/web-element/assert/value-assertions.js
Right now, if we create a test case using an async callback but do not use `await` anywhere inside the test case, failure of the newly introduced assertions in the new Element API leads to `unhandledRejection`:
```js
it('asserts using newly introduced assertions', async function(browser) {
browser.navigateTo('https://duckduckgo.com');
browser.element('input[name=q]').assert.not.visible(); // it should fail normally but leads to unhandledRejection
browser.element('input[name=q]').getText().assert.contains('Search');
});
```
With this PR, assertion failures will gracefully end the test instead of raising `unhandledRejection` which abruptly ends the test run.
If we use `then()` with the assertion promises, assertion failure leads to `unhandledRejection`. But using `then()` inside an async …
=> fix: assertion failure in new Elem API leads to unhandledRejection.

lib/api/_loaders/_base-loader.js, lib/api/_loaders/assertion.js
In certain cases, `BaseLoader.lastDeferred` is getting set to `null` in between the test execution (see issue #4265).
Although not sure yet why this is the case, it is anyway a good idea to add a null check before rejecting the `BaseLoader.lastDeferred` promise, which represents the last command or assertion added to the Nightwatch queue.
=> Add null check before rejecting BaseLoader.lastDeferred.

types/index.d.ts, types/tests/describe.test-d.ts
This PR fixes the missing type for the `driver` property available on the `NightwatchAPI` instance.
=> type: Add `driver` property to NightwatchAPI.

lib/http/request.js, test/src/index/testRequest.js
When the `keep-alive` property of the `webdriver` config is set to `true`, Nightwatch uses the same HTTP agent for all the requests made during the entirety of the test run (a feature that was added in PR #3748).
This led to an issue where if we needed to switch to a different protocol (between `https` and `https`) for certain requests during the test run, those requests would fail due to an invalid agent and gave out the following error:
```
✖ TypeError
Error while trying to create HTTP request for "/wd/hub/session/765c4e2a8c629d29ce778b2886bfef5d6634e050/url": Protocol "http:" not supported. Expected "https:"
```
This PR fixes this by allowing the agent to be changed whenever the protocol for the request changes.
=> fix: HTTP request agent not changes on protocol change.

test/src/index/testRequest.js
Introduced in #4286, the CI was running only a single test. This PR fixes that mistake.
=> Fix CI running only a single test.

lib/api/web-element/commands/getAccessibleName.js, lib/api/web-element/commands/getAriaRole.js, lib/api/web-element/scoped-element.js, test/src/api/commands/web-element/testGetAccessibleName.js, test/src/api/commands/web-element/testGetAriaRole.js, types/tests/webElement.test-d.ts, types/web-element.d.ts
This PR adds the following aliases to the new Element API:
- `getComputedLabel()` for `getAccessibleName()` command.
- `getComputedRole()` for `getAriaRole()` command.
=> Add getComputedLabel() and getComputedRole() alias commands.

types/page-object.d.ts, types/tests/page-object.test-d.ts
Fixes: #3903 
There is actually no issue with the type of the `url` property here, the issue linked above is more of a documentation issue.
By default, the url property is set to a string type [here](https://github.com/nightwatchjs/nightwatch/blob/e04ea6e490486b93c95ca0b4ddb5f70246c65127/types/page-object.d.ts#L498). To set it to a function type instead, the fifth type parameter of the `EnhancedPageObject` interface can be used:
```
export interface MyPage extends
EnhancedPageObject<{}, typeof elements, {}, {}, () => string> {}
```
See the usage of the `EnhancedPageObject` interface [here](https://github.com/nightwatchjs-community/nightwatch-typescript-boilerplate/blob/0bf15a6e8735b576b82bce9a7bb5c6beddb14de4/nightwatch/pages/FileUpload.ts#L17) for reference.
=> Improve TSDoc for page object's url property.

types/index.d.ts, types/page-object.d.ts, types/tests/page-object.test-d.ts
Fixes: #4292 
This PR adds the types for the custom commands that are made available directly over the page object sections.
It should be noted NOT all custom commands are made available directly on the section object. All the custom commands are only available on the `section.api` object while the `section` object directly contains all the custom commands EXCEPT those having a namespace. This behaviour has been accounted for in the type definition.
For example, let's say the structure of the `custom-commands` folder is as follows:
```
custom-commands/
- command1.js
- command2.js
- namespace1/
- command.js
```
The above custom commands would be available on the various APIs as follows (assuming a page-object named `myPage` with a `mySection` section):
```js
// all commands are available …
```
=> Add types for custom commands on page object sections.

types/custom-command.d.ts, types/index.d.ts, types/tests/customCommands.test-d.ts
An appliable type for `this` was missing while writing class-styled custom commands. This PR fixes that by adding a new `CommandInstance` interface that could be used while writing custom commands for `this` (as shown in the types/tests/customCommands.test-d.ts` file).
=> Add `CustomCommandInstance` interface for `this` in custom commands.

lib/api/_loaders/command.js, lib/core/treenode.js
Right now, if a custom command is written in function-style and some error occurs during the execution of that custom command, it leads to an `unhandledRejection`, leading to the closure of Nightwatch process without ending the webdriver session.
This PR fixes that behaviour by handling the error thrown inside the custom command correctly.
=> Fix unhandledRejection on error inside function-based custom commands.

lib/api/web-element/scoped-element.js, test/sampletests/webelement/findWithSuppressNotFoundErrors.js, test/src/api/commands/web-element/testFindOnErrors.js
This pull request addresses issue #4223. The suppressNotFoundErrors property in the new Element API previously suppressed all errors encountered by the WebDriver, including errors like InvalidSelectorError. This behavior was unintended, as suppressNotFoundErrors should ideally only suppress NoSuchElementError.
Updated scoped-element.js to catch and handle NoSuchElementError specifically when suppressNotFoundErrors is enabled.
Modified the logic to allow other errors, like InvalidSelectorError, to propagate as expected.
Use an invalid selector in a test command:
await browser.element.find({
selector: '@something',
suppressNotFoundErrors: true
});
Observe that InvalidSelectorError is no longer suppressed and propagates as intended.
Terminal Output
The attached screenshot shows the updated …
=> Fix #4223: Restrict suppressNotFoundErrors to NoSuchElementError

types/tests/webElement.test-d.ts, types/web-element.d.ts
=> Fix types for `dragAndDrop` command in new Elem API.

lib/api/_loaders/command.js, lib/core/asynctree.js, test/extra/commands/customCommandWithFailureClass.js, test/sampletests/withcustomcommands/sampleWithAsyncFailures.js, test/src/runner/testRunWithCustomCommands.js
If a command results in an error with `abortOnFailure` set to `true`, the node promise of the command inside the test case still gets resolved instead of getting rejected, while the queue is anyway cleared because of `abortOnFailure`.
This leads to a situation where if we chain some more commands after this command in the test case, the test would get stuck (because the queue is emptied) and hence will abort successfully. But, if the await is directly used on the command, that await will resolve and the test will continue normally since the following commands will be added to the queue after the queue is cleared.
The command promise inside the test case should instead be rejected so that the test case throws an error and thus aborting itself instead of continuing normally.
Only affects …
=> Reject custom commands node promise on abortOnFailure.

lib/core/asynctree.js, lib/core/queue.js, lib/testsuite/context.js, lib/testsuite/runnable.js, test/sampletests/withdescribe/basic2/sample.js, test/src/core/testAsyncTree.js
Right now, if a test case is written using the `async/await` syntax, the `asynctree` we use inside our queueing system gets reset after every `await`ed Nightwatch command/assertion, after which the `done()` method of the queue itself is called.
But, in between the tree getting reset and the queue's `done()` method being called, the control goes back inside the test case itself (because the `await`ed command/assertion is resolved now) and it reads the following NW commands and adds them into a new queue asynctree. So, when the `done()` method of the queue is called after that, because of [this condition](https://github.com/nightwatchjs/nightwatch/blob/44ba57c2604b81f76bae7d620236a744e99b41d3/lib/core/queue.js#L124-L126) which checks if the tree is empty or not, because the tree is …
=> Fix asynctree from getting cleared in between test case.

lib/api/web-element/assert/element-assertions.js
When using the `.assert.present()` assertion on the new Element API, if the element is not present, the following error is thrown instead of the normal assertion failure.
This PR fixes the cause of this error so that a normal assertion failure occurs.
=> Fix TypeError while using assert.present() in new Elem API.

lib/api/client-commands/perform.js
When the `.perform()` command is used with `async/await` inside a test case (`await browser.perform()`) and the callback passed to the `.perform()` command contains more than 1 Nightwatch command, the node promise returned by the `.perform()` command get resolved early (after the execution of the first Nightwatch command inside the callback).
This leads to a situation where the rest of the command inside the callback starts to overlap with the commands following the `.perform()` command inside the test case, which could give unexpected results.
=> Fix `.perform()` command node promise getting resolve early.

lib/http/request.js, lib/transport/factory.js, lib/transport/selenium-webdriver/browserstack/automateTurboScale.js, lib/transport/selenium-webdriver/browserstack/browserstack.js, test/src/index/transport/testBrowserstackTransport.js
=> Added turboScale support for apis and made necessary changes for it .

lib/runner/cli/nightwatch.conf.ejs, test/src/cli/testCliRunnerGenerate.js
The default timeout while initiating a session with BrowserStack is not long enough when testing on mobile devices or Turboscale leading to frequent connection reset errors. This PR increases the timeout to handle such cases.
=> Increase default timeout for `browserstack` env.

lib/core/client.js, lib/index.js, test/src/index/testProgrammaticApis.js
If we try to quit and relaunch the browser in between a testsuite while using Cucumber runner or Nightwatch's programmatic APIs, we cannot do so because of the below error:
```
TypeError: Error while loading the API commands: the command .acceptAlert() is already defined.
at CommandLoader.validateMethod (/Users/priyansh/Projects/nightwatch/lib/api/_loaders/_command-loader.js:54:19)
at CommandLoader.define (/Users/priyansh/Projects/nightwatch/lib/api/_loaders/_base-loader.js:330:10)
at ApiLoader.addCommandDefinitionSync (/Users/priyansh/Projects/nightwatch/lib/api/index.js:338:8)
at /Users/priyansh/Projects/nightwatch/lib/api/index.js:457:20
at /Users/priyansh/Projects/nightwatch/lib/utils/index.js:407:7
at Array.forEach (<anonymous>)
at Utils.readFolderRecursively …
```
=> Add option to not load Nightwatch APIs while launching browser.

lib/api/client-commands/debug.js, lib/testsuite/repl.js
With this enhancement in the `browser.debug()` command, users will now be able to pass the local variables from their test into the Debug mode and use them there.
On running the below example, `someLocalFunction` and `someLocalVariable` will be directly available inside the DEBUG mode (along with `browser`) and can be used like a local variable.
```js
function someLocalFunction() {
console.log('local function running');
return 'local function result';
}
describe('duckduckgo example', function() {
it('Search Nightwatch.js and check results', async function(browser) {
const someLocalVariable = 'something random';
browser
.navigateTo('http://duckduckgo.com')
.click('input[name=q]');
browser.debug({context: {someLocalVariable, someLocalFunction}});
});
});
```
=> Pass local context to `browser.debug()` command.

types/index.d.ts, types/tests/page-object.test-d.ts
A few element commands were missing on the page objects because they were declared under the wrong interface. This PR moves those commands to the correct `ElementCommands` interface.
Fixes: #4374
=> Add few missing element commands on page objects.

types/page-object.d.ts, types/tests/page-object.test-d.ts
The commands shown available directly on the page objects in TS were not consistent with the commands that are actually available on page objects in JS.
Fixes: #4367
=> Fix TS commands available on page objects.

lib/reporter/results.js
Right now, the execution time for test cases is being considered twice in the reports, which leads to individual test suites being shown as taking more time than the global run time of Nightwatch tests.
This PR fixes the same. The run time for test cases is already being considered [here](https://github.com/nightwatchjs/nightwatch/blob/0ab3004a1b2e5e65b895a4c235c04c6f2c6a2432/lib/reporter/results.js#L504) as part of sections and the consideration [here](https://github.com/nightwatchjs/nightwatch/blob/0ab3004a1b2e5e65b895a4c235c04c6f2c6a2432/lib/reporter/results.js#L484) is a duplicate.
Fixes: #4183
=> Fix double entry of test case run times in reports.

lib/reporter/index.js, lib/reporter/results.js, lib/testsuite/index.js, test/sampletests/sampleforreport/sample.js, test/sampletests/sampleforreport/sampleWithFailure.js, test/src/runner/testReporter.js
Right now, `passed`, `failed`, and `errors` count was not being saved in the `"completedSections"` part of JSON reports due to which wrong `pass/fail` status was saved and shown for certain hooks run (like `after` and global `afterEach`) irrespective of whether the commands in these hooks passed or failed.
This had a major impact on the HTML reporter and other 3rd party reporters that use "completedSections" part of report to show the status and commands run in individual secitons.
`after` hook is marked as passed even though the command failed
`after` hook marked as failed even though all commands passed
This PR fixes this undesired behaviour in reports.
=> Fix test section stats and status in reports.

lib/core/client.js
This is a bug introduced in #4358 (although this does not impact anybody, yet) where if `loadNightwatchApis` is set to `false`, the `.initialize()` method call does not return anything.
Instead, this method should always return a `NightwatchClient` instance, which it did before the changes in #4358.
=> Always return `NightwatchClient` instance from `client.initialize()` call.

lib/reporter/reporters/junit.xml.ejs, test/src/runner/testRunnerJunitOutput.js
A bug was introduced in JUnit reports in the last release. This PR fixes that.
Resolves: #4391. Thanks, @robertgorecki for raising the issue.
=> Fix `id` redefined issue in JUnit reports.

lib/api/client-commands/debug.js
The `.debug()` command has not been working since the last change made to the command in PR #4299. The command is getting resolved immediately after being executed without ever displaying the REPL interface to debug.
=> Fix `.debug()` command not working.
